ALTER TABLE CNT_SHIPMENT_ADVICE ADD IS_FROM_MULTIPLE_VENDORS NUMBER(1,0);
ALTER TABLE CNT_SHIPMENT_ADVICE ADD DESTINATION_FORWARDER_REF NVARCHAR2(1000);
ALTER TABLE CNT_SHIPMENT_ADVICE ADD DESTINATION_FORWARDER_VER NUMBER(20, 0);
ALTER TABLE CNT_SHIPMENT_ADVICE RENAME COLUMN DESTINATION_FORWARDER TO DESTINATION_FORWARDER_ID;
ALTER TABLE CNT_SHIPMENT_ADVICE MODIFY DESTINATION_FORWARDER_ID CHAR(32);
