WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK
SET DEFINE OFF

--CNT-11380
INSERT INTO CNT_TRIGGER (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, STATUS, DOC_STATUS, EDITING_STATUS,
CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, NAME, DESCRIPTION, EVENT_STR_LIST, ACTION_STR_LIST, REF_NO, ACTIVATE_BY,
HUB_DOMAIN_ID, IS_FOR_REFERENCE, IS_LATEST,CREATE_USER_NAME, UPDATE_USER_NAME)
SELECT SYS_GUID(), 1, 1, '/', 1, NULL, 'active', 'confirmed', 'admin@/', 'admin@/', SYSDATE, SYSDATE, 'Vpo released to vendor', 
'Vpo released to vendor', 'Field Changes', 'Invoke API', 'Vpo released to vendor', 1, '/', 0, 1, 'admin admin', 'admin admin'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/');

INSERT INTO CNT_TRIGGER_LISTENER (ID,REVISION,ENTITY_VERSION,DOMAIN_ID,PARENT_ID,EVENT_TYPE,EVENT_MODULE,
DOC_CONDITION_ID,REQUIRE_TYPE,ACTION_ID,DETAILS,INTERNAL_SEQ_NO,HUB_DOMAIN_ID,IS_FOR_REFERENCE, REQUIRE_TYPE_NAME)
SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/'), 1, 'vpo', 
NULL, 2, 'receiveDocument', 'Vpo delivery doc', 1, '/', 0 , 'Any'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER_LISTENER WHERE DETAILS = 'Vpo delivery doc'  AND DOMAIN_ID='/');

update CNT_TRIGGER_LISTENER set action_id='receiveDocument' where action_id='sendDocument' and details='Vpo delivery doc' and domain_id='/';

INSERT INTO CNT_TRIGGER_ACTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PARENT_ID, ACTION_TYPE, UPDATE_STATUS, REJECT_REASON_ID,
REJECT_DESCRIPTION,DEFER_DAYS,NOTIFICATION_ID,CUSTOM_CLASS, CUSTOM_PAYLOAD,DETAILS, INTERNAL_SEQ_NO, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/'), 2, null,
NULL, NULL, NULL, (select id from CNT_NOTIFICATION_PROFILE where PROFILE_NAME='VPO Send Notification Profile' and domain_id='/'), NULL, NULL, 'Vpo delivery doc', 1, '/', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER_ACTION WHERE DETAILS = 'Vpo delivery doc'  AND DOMAIN_ID='/');
--CNT-11380 end

COMMIT;   