WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK
SET DEFINE OFF

----CNT-11572 GEGIN----

INSERT INTO CNT_FORMAT_PROFILE(ID,REVISION,ENTITY_VERSION,DOMAIN_ID,VERSION,PROFILE_NAME,DIGIT_BEFORE_DECIMAL,DIGIT_AFTER_DECIMAL,ROUNDING_MODE,FORMAT,READONLY_FORMAT)
   SELECT SYS_GUID(), 1, 1, '/' , 1, 'integer-year', 18, 0 , 'HALF_UP', '####', '####' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/');


----CNT-11572 END----

COMMIT;