WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK
SET DEFINE OFF

----CNT-11572 GEGIN----

INSERT INTO CNT_FORMAT_PROFILE(ID,REVISION,ENTITY_VERSION,DOMAIN_ID,VERSION,PROFILE_NAME,DIGIT_BEFORE_DECIMAL,DIGIT_AFTER_DECIMAL,ROUNDING_MODE,FORMAT,READONLY_FORMAT)
   SELECT SYS_GUID(), 1, 1, '/' , 1, 'integer-year', 18, 0 , 'HALF_UP', '####', '####' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/');

INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'Vendor', 1, 'yearEstablished', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='Vendor' AND FIELD_ID='yearEstablished' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'VendorCust', 1, 'relateSince', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='VendorCust' AND FIELD_ID='relateSince' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
 INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'VendorKeyCustomer', 1, 'relateSince', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='VendorKeyCustomer' AND FIELD_ID='relateSince' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
 INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'VendorHistorical', 1, 'year', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='VendorHistorical' AND FIELD_ID='year' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
 INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'VendorFact', 1, 'relateSince', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='VendorFact' AND FIELD_ID='relateSince' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
 INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'Cust', 1, 'yearEstablished', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='Cust' AND FIELD_ID='yearEstablished' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
 INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'Forwarder', 1, 'yearEstablished', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='Forwarder' AND FIELD_ID='yearEstablished' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));
 
 INSERT INTO CNT_FORMAT_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, INTERNAL_SEQ_NO, PROFILE_ID, APPLY_ENTITY_NAME, APPLY_ENTITY_VERSION, FIELD_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', NULL, (SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'), 'Fact', 1, 'yearEstablished', '/', 0 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CNT_FORMAT_FIELD WHERE DOMAIN_ID='/' AND APPLY_ENTITY_NAME='Fact' AND FIELD_ID='yearEstablished' AND 
 PROFILE_ID=(SELECT ID FROM CNT_FORMAT_PROFILE WHERE PROFILE_NAME = 'integer-year' AND DOMAIN_ID='/'));

----CNT-11572 END----

COMMIT;