--CNT-11380
update CNT_TRIGGER_LISTENER set action_id='receiveDocument' where action_id='sendDocument' and details='Vpo delivery doc' and domain_id='/';

--end of CNT-11380	

--CNT-11058 BEGIN--

DECLARE
    CURSOR CSELECT
    IS
        SELECT ID,HUB_DOMAIN_ID
        FROM CNT_DOMAIN 
        WHERE ID NOT IN ('backend', 'test')
            AND NOT EXISTS (
                 SELECT 1  
                 FROM CNT_EXTERNAL_ACCESS_REQUEST ear
                 WHERE ear.EXTERNAL_DOMAIN_TYPE = 'new'
                AND CNT_DOMAIN.ID = ear.EXTERNAL_DOMAIN_ID
                );
BEGIN
FOR SELECT_RECORD IN CSELECT
LOOP
    INSERT INTO CNT_DEFAULT_PROFILE (
    ID, REVISION, ENTITY_VERSION, STATUS, DOC_STATUS, EDITING_STATUS, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, REF_ENTITY_NAME, HUB_DOMAIN_ID, IS_FOR_REFERENCE, IS_LATEST, CREATE_USER_NAME, DOMAIN_ID ,REF_NO
    )
    SELECT LOWER(SYS_GUID()), 1, 1, NULL, 'active', 'confirmed', 'system', NULL, SYSDATE, NULL, 'DataListType', SELECT_RECORD.HUB_DOMAIN_ID, 0, 1, 'system', SELECT_RECORD.ID , 'S'|| TO_CHAR(SYSDATE,'YY') || '-'|| LPAD(TO_CHAR(NVL((SELECT NEXT_VAL FROM CNT_SEQ_DEF WHERE DOMAIN_ID = SELECT_RECORD.ID AND SEQ_ID ='CBX_SEQ_DEFAULT_PROFILE_REF_NO'),0)),6,'0')
    FROM DUAL 
    WHERE NOT EXISTS (SELECT 1 FROM CNT_DEFAULT_PROFILE WHERE DOMAIN_ID = SELECT_RECORD.ID  AND REF_ENTITY_NAME = 'DataListType');

    INSERT INTO CNT_DEFAULT_PROFILE_FIELD ( 
    ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, MASTER_SEQ_NO, SEQ_NO, SECTION_ID, FIELD_ID, VALUE_TYPE, DEFAULT_VALUE, OVERRIDE_TEMPLATE, HUB_DOMAIN_ID, IS_FOR_REFERENCE, VALUE_TYPE_NAME
    )
    SELECT LOWER(SYS_GUID()), 1, 1, SELECT_RECORD.ID, PROF.ID, 1, 1, NULL, 'applyToEntity', 'fixed', 2, NULL, SELECT_RECORD.HUB_DOMAIN_ID, 0, NULL 
    FROM CNT_DEFAULT_PROFILE PROF
    WHERE PROF.DOMAIN_ID = SELECT_RECORD.ID AND PROF.REF_ENTITY_NAME = 'DataListType' 
    AND NOT EXISTS (SELECT 1 FROM CNT_DEFAULT_PROFILE_FIELD WHERE DOMAIN_ID = SELECT_RECORD.ID AND SECTION_ID IS NULL AND FIELD_ID = 'applyToEntity');

    INSERT INTO CNT_CODELIST_LINK_INFO(
    ID, REVISION, ENTITY_VERSION, DOMAIN_ID, REF_ID, REF_ENTITY, REF_FIELD, CODELIST_DOMAIN, CODELIST_NAME, CODELIST_VERSION, CODELIST_CODE, CREATE_USER, CREATED_ON, HUB_DOMAIN_ID, IS_FOR_REFERENCE
    ) 
    SELECT LOWER(SYS_GUID()), CDPF.REVISION, CDPF.ENTITY_VERSION, SELECT_RECORD.ID, CDPF.ID, 'DefaultProfileField', 'valueType', '/', 'DEFAULT_VALUE_TYPE', 1, 'fixed', 'system', SYSDATE, SELECT_RECORD.HUB_DOMAIN_ID, 0 
    FROM CNT_DEFAULT_PROFILE_FIELD CDPF 
    WHERE CDPF.DOMAIN_ID =  SELECT_RECORD.ID AND CDPF.SECTION_ID IS NULL AND CDPF.FIELD_ID = 'applyToEntity' AND CDPF.VALUE_TYPE = 'fixed' AND NOT EXISTS (SELECT 1 FROM CNT_CODELIST_LINK_INFO WHERE DOMAIN_ID =  SELECT_RECORD.ID AND REF_ID = CDPF.ID);

    UPDATE CNT_SEQ_DEF SET NEXT_VAL = NEXT_VAL +1 WHERE SEQ_ID= 'CBX_SEQ_DEFAULT_PROFILE_REF_NO' AND DOMAIN_ID = SELECT_RECORD.ID;

END Loop;
END;
/

--CNT-11058 END---
