DELETE FROM CNT_FIELD_PATH_ATTRIBUTES WHERE PARENT_ID IN (SELECT ID FROM CNT_FIELD_PATH WHERE ROWID IN (SELECT rid FROM (SELECT ROWID rid, ROW_NUMBER () OVER (PARTITION BY X_PATH ORDER BY ROWID) rn FROM CNT_FIELD_PATH) WHERE rn <> 1));
DELETE FROM CNT_FIELD_PATH WHERE ROWID IN (SELECT rid FROM (SELECT ROWID rid, ROW_NUMBER () OVER (PARTITION BY X_PATH ORDER BY ROWID) rn FROM CNT_FIELD_PATH) WHERE rn <> 1);

ALTER TABLE CNT_FIELD_PATH ADD CONSTRAINT UK_FIELD_PATH1 UNIQUE (X_PATH);

DELETE FROM CNT_LABEL WHERE ROWID IN (SELECT rid FROM (SELECT ROWID rid, ROW_NUMBER () OVER (PARTITION BY LABEL_ID,LOCALE,DOMAIN_ID,TYPE,MODULE_CODE ORDER BY ROWID) rn FROM CNT_LABEL) WHERE rn <> 1);

ALTER TABLE CNT_LABEL ADD CONSTRAINT UK_LABEL1 UNIQUE (LABEL_ID,LOCALE,DOMAIN_ID,TYPE,MODULE_CODE);

DELETE FROM CNT_RULE_ACTION WHERE ROWID IN (SELECT rid FROM (SELECT ROWID rid, ROW_NUMBER () OVER (PARTITION BY ACCESS_OBJECT_ID,ROLE_ID,ACTION_ID,CONDITION_ID,ACCESS_RIGHT ORDER BY ROWID) rn FROM CNT_RULE_ACTION) WHERE rn <> 1);

ALTER TABLE CNT_RULE_ACTION ADD CONSTRAINT UK_RULE_ACTION1 UNIQUE (ACCESS_OBJECT_ID,ROLE_ID,ACTION_ID,CONDITION_ID,ACCESS_RIGHT);


ALTER TABLE CNT_NAVI_MODULE ENABLE PRIMARY KEY;