WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK;
SET DEFINE OFF;

/*
INSERT INTO CNT_MEMBER_HCL_NODE (
	ID, REVISION, ENTITY_VERSION, DOMAIN_ID, MEMBER_ID, MEMBER_TYPE, HCL_NODE_ID
)
SELECT LOWER(SYS_GUID()), 1, 1, u.DOMAIN_ID, u.ID, 1, n.ID
FROM CNT_HCL h
INNER JOIN CNT_HCL_NODE n ON h.ID = n.HCL_ID
INNER JOIN CNT_USER u ON u.DOMAIN_ID = h.DOMAIN_ID
WHERE h.NAME = 'SPECIFICATION_TYPE'
AND u.DOMAIN_ID = '/'
AND NOT EXISTS (
	SELECT 1
	FROM CNT_MEMBER_HCL_NODE mn
	WHERE mn.DOMAIN_ID = u.DOMAIN_ID
	AND mn.MEMBER_ID = u.ID
	AND mn.MEMBER_TYPE = 1
	AND mn.HCL_NODE_ID = n.ID
);
*/

--// Assign all HCL Node to 'ADMINISTRATOR' user group
INSERT INTO CNT_MEMBER_HCL_NODE (
	ID, REVISION, ENTITY_VERSION, DOMAIN_ID, MEMBER_ID, MEMBER_TYPE, HCL_NODE_ID
)
SELECT LOWER(SYS_GUID()), 1, 1, g.DOMAIN_ID, g.ID, 2, n.ID
FROM CNT_HCL_NODE n
INNER JOIN CNT_GROUP g ON g.DOMAIN_ID = n.DOMAIN_ID
WHERE g.NAME = 'ADMINISTRATORS'
AND g.DOMAIN_ID = '/'
AND NOT EXISTS (
	SELECT 1
	FROM CNT_MEMBER_HCL_NODE mn
	WHERE mn.DOMAIN_ID = g.DOMAIN_ID
	AND mn.MEMBER_ID = g.ID
	AND mn.MEMBER_TYPE = 2
	AND mn.HCL_NODE_ID = n.ID
);

COMMIT;
