INSERT INTO CNT_SYSTEM_FILE (
  ID, REVISION, ENTITY_VERSION, VERSION, DOMAIN_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE, IS_LATEST,
  CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, DOC_STATUS, EDITING_STATUS,
  SYSTEM_FILE_ID, 
  FILE_NAME, FILE_TYPE, DESCRIPTION,
  REF_NO)
SELECT LOWER(SYS_GUID()), 0, 1, 1, '/', '/', 0, 1,
  'system', 'system', SYSDATE, SYSDATE, 'active', 'confirmed',
  'VIEWEXP_' || Upper(regexp_replace(NAME, '([A-Z])', '_\1')), 
  'View: ' || NAME, '2', 'Excel Template used in view: ' || NAME,
  'VIEWEXP_' || Upper(regexp_replace(NAME, '([A-Z])', '_\1'))
FROM cnt_view
WHERE base_view_id IS NULL
AND domain_id = '/' 
AND hub_domain_id = '/'
AND module_id NOT IN ('ALL', 'all')
AND NAME NOT LIKE 'pop%'
AND NOT EXISTS (
  SELECT 1 
  FROM CNT_SYSTEM_FILE 
  WHERE SYSTEM_FILE_ID = 'VIEWEXP_' || Upper(regexp_replace(cnt_view.NAME, '([A-Z])', '_\1'))
  AND DOMAIN_ID = '/'
);

INSERT INTO CNT_CODELIST_LINK_INFO (
  ID, REVISION, ENTITY_VERSION, DOMAIN_ID, HUB_DOMAIN_ID, IS_FOR_REFERENCE,
  REF_ID, REF_ENTITY, REF_FIELD, CODELIST_DOMAIN, CODELIST_NAME, 
  CODELIST_TYPE_ID,
  CODELIST_VERSION,CODELIST_CODE, 
  CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON
)
SELECT LOWER(sys_guid()), 0, 1, '/', '/', 0, 
  CSF.ID, 'SystemFile', 'fileType', CSF.DOMAIN_ID, 'SYSTEM_FILE_TYPE',
  (SELECT TYPE_ID FROM CNT_CODELIST_BOOK WHERE DOMAIN_ID = '/' AND NAME = 'SYSTEM_FILE_TYPE'),
  1, CSF.FILE_TYPE,
  CSF.CREATE_USER, CSF.UPDATE_USER, sysdate, sysdate
FROM CNT_SYSTEM_FILE CSF 
WHERE DOMAIN_ID = '/' AND
NOT EXISTS (
  SELECT 1 
  FROM CNT_CODELIST_LINK_INFO CSLI 
  WHERE DOMAIN_ID = '/' 
  AND CSLI.REF_ID = CSF.ID 
  AND REF_FIELD = 'fileType'
);
