--Init PasswordPolicy
INSERT INTO CNT_PASSWORD_POLICY (
    ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, DOC_STATUS, MAX_LENGTH, MIN_LENGTH, UPPER_CASE_CHARS,
    LOWER_CASE_CHARS, DIGIT, PUNCTUATION, PROHIBIT_CHARS, ACCOUNT_NAME_PROHIBIT, HISTORY_SIZE, MAX_LIFETIME, MIN_LIFETIME,
    MAX_ATTEMPTS, ATTEMPT_INTERVAL, UNLOCK_INTERVAL, UPPER_CASE_REQUIRED, LOWER_CASE_REQUIRED, DIGIT_REQUIRED, PUNCTUATION_REQUIRED,
    NUM_OF_RULES, RESET_INTERVAL,
    CREATE_USER, CREATED_ON, IS_LATEST, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
SELECT
    sys_guid(), 1, 1, '/', 1, 'active', null, 8, 1,
    1, 1, 1, null, 1, 1, 42, 0, 
    5, 30, 30, null, null, null, null,
    3, 120, 
    'system', sysdate, 1, '/', 0
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 from CNT_PASSWORD_POLICY WHERE DOMAIN_ID = '/'
);