SET DEFINE OFF; 
DELETE FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID = '/';
----------------Start CNT-7826 ----------------------------------------------------------------
---Plan tab
-----Program module---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'program', (SELECT ID FROM CNT_VIEW WHERE NAME='catalogActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'program' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='catalogActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'program', (SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'program' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

------------------------------------------Item module --------------------------------------------
-------Specification---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='itemSpecView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemSpecView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Specification---------
-------Catalog---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='showroomView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='showroomView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Catalog---------
-------Brief ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Brief ---------
-------Quotation ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item',(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Quotation ---------
-------Request for Quotations ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT) 
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item',(SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Request for Quotations ---------
-------Offer Sheet ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Offer Sheet ---------
-------Customer PO ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='cpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Customer PO ---------
-------Vendor PO ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '8', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Vendor PO ---------
-------Quality Checklist ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '9', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Quality Checklist ---------
-------Inspection Checklist ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='inspetchkItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '10', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='inspetchkItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Inspection Checklist ---------
-------Shipment Advice ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '11', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Shipment Advice ---------
-------Shipment Booking ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '12', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Shipment Booking ---------
-------Customer Invoice ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '13', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Customer Invoice ---------
-------Customer ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '14', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Customer ---------
----ArtworkPackaging module for CNT-10312---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='artworkPackagingItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '15', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='artworkPackagingItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
----ArtworkPackaging module---

----Project module for CNT-10312---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '16', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'item' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
----Project module---
------------------------------------------------------item------------------------------------------------------
-----------------------------------------------------Specification----------------------------------------------
-------Item ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Item ---------
-------Catalog ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='showroomView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='showroomView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Catalog ---------
-------Brief ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Brief ---------
-------Quotation ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Quotation ---------
-------Request for Quotations ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Request for Quotations ---------
-------Offer Sheet ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Offer Sheet---------
-------Customer PO ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='cpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Customer PO---------
------- Vendor PO---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '8', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Vendor PO ---------
-------Quality Checklist ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON,
UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '9', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Quality Checklist---------
---------Project module for CNT-10312---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '10', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'spec' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
----------Project module---
-----------------------------------------------------------Specification-----------------------------------------
------------------------------------------------------------Catalog---------------------------------------
-------Program ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'catalog', (SELECT ID FROM CNT_VIEW WHERE NAME='programActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'catalog' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='programActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Program ---------
-------Item ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'catalog', (SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'catalog' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Item ---------
------- Brief---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'catalog', (SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'catalog' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Brief---------
-----------------------------------------------------------Catalog---------------------------------------
-----------------------------------------------------Artwork & Packaging for CNT-10312----------------------------------------------
-------Item ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'artworkPackaging',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'artworkPackaging' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Item ---------
----Project module---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'artworkPackaging', (SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'artworkPackaging' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
----Project module---
----------------------------------------------------Artwork & Packaging--------------------------------------------

----------------------------------------------------Project for CNT-10312--------------------------------------------
-------Program ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'project', (SELECT ID FROM CNT_VIEW WHERE NAME='programActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'project' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='programActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Program ---------
------- Item---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'project', (SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'project' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Item---------
------- Artwork & Packaging---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'project', (SELECT ID FROM CNT_VIEW WHERE NAME='artworkPackagingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'project' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='artworkPackagingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Artwork & Packaging---------
----------- Brief ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'project',(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'project' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Brief  --------------

------- Quotation---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'project',(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'project' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Quotation---------
----------------------------------------------------Project--------------------------------------------
------------------------------------------------------------Brief------------------------------------------
------- Item---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Item---------
-------Catalog ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='showroomView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='showroomView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Catalog ---------
------- Quotation---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Quotation---------
-------Request for Quotations ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Request for Quotations ---------

-------Quality Checklist ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Quality Checklist---------

------- Customer---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Customer---------

-------Vendor ---------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Vendor---------
-------Project for CNT-10312---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'brief', (SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '8', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'brief' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------Project-----------
---------------------------------------------------------------------Brief---------------------------------------
----------------------------------------------------------------------Quotation---------------------------------
------- Item----------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vq', (SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
--------- Item ---------
-------Brief ----------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vq', (SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Brief---------
------- Request for Quotations----------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vq',(SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='rfqItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
---------Request for Quotations ---------
-----------Offer Sheet  ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vq',(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------Offer Sheet--------------
----------Project for CNT-10312---
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATE_USER_NAME, UPDATE_USER_NAME, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', 'system', 'system', SYSDATE, SYSDATE, 'vq', (SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='projectItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
----------Project module---
-----------------------------------------------------------------------Quotation-----------------------------------------------
------------------------------------------------------------------------Request for Quotations-------------------------------------------
----------- Item ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'rfq',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'rfq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Item  --------------
----------- Brief ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'rfq',(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'rfq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Brief  --------------
----------- Quotation ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'rfq',(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'rfq' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Quotation  --------------

------------------------------------------------------------------------Request for Quotations-------------------------------------------
------------------------------------------------------------------------Offer Sheet-------------------------------------------
-----------Program  ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'offersheet',(SELECT ID FROM CNT_VIEW WHERE NAME='programActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'offersheet' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='programActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Program  --------------
----------- Item ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'offersheet',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'offersheet' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Item  --------------
----------- Quotation ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'offersheet',(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'offersheet' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vqActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------  Quotation --------------
----------- Customer PO ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'offersheet',(SELECT ID FROM CNT_VIEW WHERE NAME='cpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'offersheet' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Customer PO  --------------
----------- Customer ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'offersheet',(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'offersheet' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Customer  --------------
----------- Factory ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'offersheet',(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'offersheet' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------  Factory --------------
------------------------------------------------------------------------Offer Sheet-------------------------------------------
------------------------------------------------------------------------Customer PO-------------------------------------------
----------- Item ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Item  --------------
----------- Offer Sheet ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Offer Sheet  --------------
----------- Vendor PO ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------  Vendor PO --------------
----------- Shipment Advice ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Shipment Advice  --------------
----------- Shipment Booking ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Shipment Booking  --------------
----------- Customer Invoice ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------  Customer Invoice --------------
----------- Customer ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cpo',(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------  Customer --------------
------------------------------------------------------------------------Customer PO-------------------------------------------
------------------------------------------------------------------------Vendor PO-------------------------------------------
----------- Item ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Item --------------
----------- Customer PO ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------Customer PO  --------------
----------- Quality Checklist ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='qcItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='qcItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Quality Checklist --------------
----------- Inspection Checklist ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='inspetchkItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='inspetchkItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Inspection Checklist --------------
----------- Shipment Advice ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Shipment Advice --------------
----------- Shipment Booking ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Shipment Booking --------------
----------- Customer ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Customer --------------
----------- Vendor ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '8', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Vendor --------------
----------- Factory ------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vpo',(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '9', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vpo' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------ Factory --------------
------------------------------------------------------------------------Vendor PO-------------------------------------------

------Master tab
   ---Customer module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cust',(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cust' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cust',(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cust' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cust',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cust' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cust',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cust' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cust',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cust' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'cust',(SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'cust' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

----Vendor module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vendor',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vendor' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vendor',(SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vendor' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='qcActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vendor',(SELECT ID FROM CNT_VIEW WHERE NAME='inspeCheckActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vendor' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='inspeCheckActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vendor',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vendor' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'vendor',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'vendor' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

---Factory module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'fact',(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'fact' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='offerSheetsItemsView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'fact', (SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'fact' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoQtyItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'fact', (SELECT ID FROM CNT_VIEW WHERE NAME='inspeCheckActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'fact' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='inspeCheckActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'fact',(SELECT ID FROM CNT_VIEW WHERE NAME='factAutitsActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'fact' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='factAutitsActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

---Forwarder module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'forwarder',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'forwarder' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'forwarder',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'forwarder' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

----Logistic tab
  ---Shipment Advice module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentBookingActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice',(SELECT ID FROM CNT_VIEW WHERE NAME='forwActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='forwActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

---ShipmentBooking module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '5', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '6', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentBooking',(SELECT ID FROM CNT_VIEW WHERE NAME='forwActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '7', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentBooking' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='forwActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

---CustInv module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'custInv',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'custInv' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'custInv',(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'custInv' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='cpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'custInv',(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'custInv' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

----Quality tab
  --qc module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'qc',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'qc' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'qc',(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'qc' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='briefActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'qc',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'qc' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'qc',(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'qc' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

---inspectcheck module
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'inspectcheck',(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'inspectcheck' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'inspectcheck',(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '2', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'inspectcheck' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vpoActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'inspectcheck',(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '3', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'inspectcheck' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='vendorActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'inspectcheck',(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '4', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'inspectcheck' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

---factAudit moudle
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION,CREATE_USER, UPDATE_USER, CREATED_ON,UPDATED_ON, MODULE,VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'factAudit',(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'factAudit' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='factActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));
------------------------------End CNT-7826------------------------------------------------------------------


---CNT-10327 BEGIN-----------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'component', (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemActiveView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemActiveView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');


INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'component', (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemSpecView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemSpecView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');


INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'component', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoActiveView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoActiveView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');


INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'component', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorActiveView' AND MODULE_ID = 'vendor' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'component' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorActiveView' AND MODULE_ID = 'vendor' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');


INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'spec'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'spec' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'item'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'item' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendor', (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL), 
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'componentActiveView' AND MODULE_ID = 'component' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL) AND DOMAIN_ID = '/');
---CNT-10327 END-----------

--//BEG:CNT-10931-----------------------------------------------------------------------
--------------------------------------------------custInv-------------------------------------------------------------
--item------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'custInv', (SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL),
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'custInv'), '1', '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS ( 
SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'custInv' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='itemActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL));
--item------------------
--shipmentAdvice--------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'custInv', (SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL),
0, (SELECT nvl(MAX(SEQUENCE), 0) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'custInv'), '1', '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS ( 
SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'custInv' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='shipmentAdviceActiveView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/' AND BASE_VIEW_ID IS NULL));
--shipmentAdvice--------

--------------------------------------------------custInv-------------------------------------------------------------

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT)
SELECT LOWER(SYS_GUID()), 0, 1, '/', 1, 'system', 'system', SYSDATE, SYSDATE, 'shipmentAdvice', (SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'), '0', '1', '1' FROM DUAL
WHERE NOT EXISTS ( SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE DOMAIN_ID='/' AND MODULE = 'shipmentAdvice' AND VIEW_ID=(SELECT ID FROM CNT_VIEW WHERE NAME='custInvQtyByItemView' AND CREATE_USER_NAME = 'DUMMY_SYSTEM_ID' AND DOMAIN_ID = '/'));

--//END:CNT-10931-----------------------------------------------------------------------