SET DEFINE OFF; 


INSERT INTO CNT_TRIGGER (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, STATUS, DOC_STATUS, EDITING_STATUS,
CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, NAME, DESCRIPTION, EVENT_STR_LIST, ACTION_STR_LIST, REF_NO, ACTIVATE_BY,
HUB_DOMAIN_ID, IS_FOR_REFERENCE, IS_LATEST,CREATE_USER_NAME, UPDATE_USER_NAME)
SELECT SYS_GUID(), 1, 1, '/', 1, NULL, 'active', 'confirmed', 'admin@/', 'admin@/', SYSDATE, SYSDATE, 'Vpo released to vendor', 
'Vpo released to vendor', 'Field Changes', 'Invoke API', 'Vpo released to vendor', 1, '/', 0, 1, 'admin admin', 'admin admin'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/');
 
INSERT INTO CNT_TRIGGER_ACTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PARENT_ID, ACTION_TYPE, UPDATE_STATUS, REJECT_REASON_ID,
REJECT_DESCRIPTION,DEFER_DAYS,NOTIFICATION_ID,CUSTOM_CLASS, CUSTOM_PAYLOAD,DETAILS, INTERNAL_SEQ_NO, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/'), 3, 'releasedToVendor',
NULL, NULL, NULL, NULL, 'com.core.cbx.vpo.trigger.VpoReleasedToVendorTriggerAction', NULL, 'Update status to releasedToVendor', 1, '/', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER_ACTION WHERE CUSTOM_CLASS = 'com.core.cbx.vpo.trigger.VpoReleasedToVendorTriggerAction'  AND DOMAIN_ID='/');

INSERT INTO CNT_TRIGGER_LISTENER (ID,REVISION,ENTITY_VERSION,DOMAIN_ID,PARENT_ID,EVENT_TYPE,EVENT_MODULE,
DOC_CONDITION_ID,REQUIRE_TYPE,ACTION_ID,DETAILS,INTERNAL_SEQ_NO,HUB_DOMAIN_ID,IS_FOR_REFERENCE, REQUIRE_TYPE_NAME)
SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/'), 2, 
'vpo', NULL, 2, NULL, 'Vpo status changes from $ANY to releasedToVendor', 1, '/', 0 , 'Any'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER_LISTENER WHERE DETAILS = 'Vpo status changes from $ANY to releasedToVendor'  AND DOMAIN_ID='/');
 
INSERT INTO CNT_TRIGGER_LISTENER_CRITERIA (ID, REVISION, ENTITY_VERSION,DOMAIN_ID,PARENT_ID,
SOURCE_ID,FROM_VALUE,TO_VALUE,INTERNAL_SEQ_NO,HUB_DOMAIN_ID,IS_FOR_REFERENCE)
SELECT SYS_GUID(),1, 1, '/', (SELECT ID FROM CNT_TRIGGER_LISTENER WHERE DETAILS = 'Vpo status changes from $ANY to releasedToVendor'  AND DOMAIN_ID='/'
AND PARENT_ID=(SELECT ID FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/')), 'status', '$ANY', 'releasedToVendor',
1, '/', 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_TRIGGER_LISTENER_CRITERIA WHERE DOMAIN_ID='/' AND SOURCE_ID ='status' AND FROM_VALUE='$ANY'
AND TO_VALUE='releasedToVendor' AND PARENT_ID= (SELECT ID FROM CNT_TRIGGER_LISTENER WHERE DETAILS = 'Vpo status changes from $ANY to releasedToVendor'  AND DOMAIN_ID='/'
AND PARENT_ID=(SELECT ID FROM CNT_TRIGGER WHERE NAME ='Vpo released to vendor' AND DOMAIN_ID='/')));