

-- CNT-10966 BEGIN --
CREATE OR REPLACE PROCEDURE SP_INIT_ROLE_UI_TABLE(I_DOMAIN_ID IN VARCHAR2)
AS
        -- 01 RULE_ACTION
        CURSOR C_RCAOS IS SELECT DISTINCT ROLE_ID, CONDITION_ID, ACCESS_OBJECT_ID FROM CNT_RULE_ACTION WHERE DOMAIN_ID = I_DOMAIN_ID;
    CURSOR C_RULE_ACTIONS IS SELECT DISTINCT ROLE_ID, ACCESS_OBJECT_ID, CONDITION_ID, ACTION_ID FROM CNT_RULE_ACTION WHERE DOMAIN_ID = I_DOMAIN_ID;
   
    -- 02 RULE_UI
    CURSOR C_RULE_RIGHT_CONDITION_UI IS SELECT DISTINCT ROLE_ID, CONDITION_ID , ACCESS_RIGHT ,UI_ID FROM CNT_RULE_UI WHERE DOMAIN_ID = I_DOMAIN_ID;
    CURSOR C_RULE_UIS IS SELECT DISTINCT ROLE_ID, ACCESS_OBJECT_ID, CONDITION_ID , ACCESS_RIGHT ,UI_ID FROM CNT_RULE_UI WHERE DOMAIN_ID = I_DOMAIN_ID;
    
    -- 03 RULE_FIELD_DENY
    CURSOR C_ROLE_FIELDS IS SELECT DISTINCT ROLE_ID, FIELD_ID FROM CNT_RULE_FIELD_DENY WHERE DOMAIN_ID = I_DOMAIN_ID;
    CURSOR C_RULE_FIELD_DENYS IS SELECT DISTINCT ROLE_ID, ACCESS_OBJECT_ID, FIELD_ID FROM CNT_RULE_FIELD_DENY WHERE DOMAIN_ID = I_DOMAIN_ID;
    GUID CHAR(32);
BEGIN
    --************* 01 RULE_ACTION ***************
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleActionAdmin' AND FIELD_ID='objectId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleActionAdmin' AND FIELD_ID='actionId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleActionAdmin' AND FIELD_ID='conditionId' AND DOMAIN_ID = I_DOMAIN_ID;
    
    DELETE FROM CNT_RULE_ACTION_ADMIN WHERE DOMAIN_ID = I_DOMAIN_ID;
    
    FOR C_CONDITION_AO IN C_RCAOS
    LOOP
            GUID:=LOWER(sys_guid());
            INSERT INTO CNT_RULE_ACTION_ADMIN (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, ROLE_ID)
            SELECT GUID, 1, 1, I_DOMAIN_ID, C_CONDITION_AO.ROLE_ID FROM DUAL;
        INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
            SELECT LOWER(sys_guid()), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleActionAdmin', 'objectId', 'AccessObject', C_CONDITION_AO.ACCESS_OBJECT_ID FROM DUAL;
        INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
            SELECT LOWER(sys_guid()), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleActionAdmin', 'conditionId', 'Condition', C_CONDITION_AO.CONDITION_ID FROM DUAL;
        
        FOR C_RULE_ACTION IN C_RULE_ACTIONS
        LOOP
            IF C_CONDITION_AO.ACCESS_OBJECT_ID = C_RULE_ACTION.ACCESS_OBJECT_ID 
            AND C_CONDITION_AO.CONDITION_ID = C_RULE_ACTION.CONDITION_ID
            AND C_CONDITION_AO.ROLE_ID = C_RULE_ACTION.ROLE_ID THEN
                    INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
                SELECT LOWER(sys_guid()), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleActionAdmin', 'actionId', 'AccessObjectAction', AOA.ID 
                FROM CNT_ACCESS_OBJECT_ACTION AOA WHERE C_RULE_ACTION.ACCESS_OBJECT_ID = AOA.ACCESS_OBJECT_ID AND C_RULE_ACTION.ACTION_ID = AOA.ACTION_ID AND AOA.DOMAIN_ID = I_DOMAIN_ID;
            END IF;
        END LOOP;
    END LOOP;
    
    --************* 02 RULE_UI *********************************************** 
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleUiAdmin' AND FIELD_ID='objectId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleUiAdmin' AND FIELD_ID='conditionId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_RULE_UI_ADMIN WHERE DOMAIN_ID = I_DOMAIN_ID;
    
    FOR CUR_RRCU IN C_RULE_RIGHT_CONDITION_UI
    LOOP
            GUID:=LOWER(sys_guid());
            INSERT INTO CNT_RULE_UI_ADMIN (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, ROLE_ID, ACCESS_RIGHT, UI_FIELD_ID)
            SELECT GUID, 1, 1, I_DOMAIN_ID, CUR_RRCU.ROLE_ID, CUR_RRCU.ACCESS_RIGHT, CUR_RRCU.UI_ID FROM DUAL;
        INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
            SELECT LOWER(sys_guid()), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleUiAdmin', 'conditionId', 'Condition', CUR_RRCU.CONDITION_ID FROM DUAL;
        FOR C_RULE_UI IN C_RULE_UIS
        LOOP
            IF C_RULE_UI.ROLE_ID = CUR_RRCU.ROLE_ID 
                AND C_RULE_UI.CONDITION_ID = CUR_RRCU.CONDITION_ID
                AND C_RULE_UI.ACCESS_RIGHT = CUR_RRCU.ACCESS_RIGHT
                AND C_RULE_UI.UI_ID = CUR_RRCU.UI_ID THEN
                    INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
                    SELECT LOWER(sys_guid()), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleUiAdmin', 'objectId', 'AccessObject', C_RULE_UI.ACCESS_OBJECT_ID FROM DUAL;
            END IF;
        END lOOP;
        END LOOP;
        
        --****************** 03 RULE_FIELD_DENY ***********************************************
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleFieldDenyAdmin' AND FIELD_ID='objectId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_RULE_FIELD_DENY_ADMIN WHERE DOMAIN_ID = I_DOMAIN_ID;
        
        FOR C_ROLE_FIELD IN C_ROLE_FIELDS
    LOOP
            GUID:=LOWER(sys_guid());
            INSERT INTO CNT_RULE_FIELD_DENY_ADMIN(ID, REVISION, ENTITY_VERSION, DOMAIN_ID, ROLE_ID, FIELD_ID)
            SELECT GUID, 1, 1, I_DOMAIN_ID, C_ROLE_FIELD.ROLE_ID, C_ROLE_FIELD.FIELD_ID FROM DUAL;
       
        FOR C_RULE_FIELD_DENY IN C_RULE_FIELD_DENYS
        LOOP
            IF C_ROLE_FIELD.ROLE_ID = C_RULE_FIELD_DENY.ROLE_ID 
                AND C_ROLE_FIELD.FIELD_ID = C_RULE_FIELD_DENY.FIELD_ID THEN
                    INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
                    SELECT LOWER(sys_guid()), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleFieldDenyAdmin', 'objectId', 'AccessObject', C_RULE_FIELD_DENY.ACCESS_OBJECT_ID FROM DUAL;
            END IF;
        END lOOP;
        END LOOP;
        
END;
/

CALL SP_INIT_ROLE_UI_TABLE('/');
 
DROP PROCEDURE SP_INIT_ROLE_UI_TABLE;
-- CNT-10966 END --

