WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK
SET DEFINE OFF

-- #1 add one more profile for RfqSend action.
 INSERT INTO CNT_VALIDATION_PROFILE
 (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_NAME , REF_ENTITY_NAME, REF_ENTITY_VERSION, ACTION, ENABLED, CREATE_USER, CREATED_ON)
 VALUES (LOWER(SYS_GUID()), 0, 1, '/', 'Default Data Validation Profile Rfq[ver:1]', 'Rfq', 1, 'RfqSend', 1, 'system', systimestamp);

-- #2 add one more validation rule for RfqSend action.
 INSERT INTO CNT_VALIDATION_RULE
 (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
 select LOWER(SYS_GUID()), 0, 1, '/',  id, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
 from CNT_VALIDATION_PROFILE CVP where ACTION = 'RfqSend' AND CVP.domain_id = '/';

-- #3 copy all validation fields validata from "save" action
 INSERT INTO CNT_VALIDATION_FIELD
 (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, LINE_NO, ENABLED)
 select LOWER(SYS_GUID()), VF.REVISION, VF.ENTITY_VERSION, VF.DOMAIN_ID, VR.ID AS VALIDATION_RULE_ID, VF.REF_ENTITY_NAME, VF.FIELD_ID, VF.FIELD_PATH, VF.LINE_NO, VF.ENABLED 
 from CNT_VALIDATION_FIELD VF, CNT_VALIDATION_RULE VR
 WHERE VF.VALIDATION_RULE_ID IN
 (SELECT VR.ID FROM CNT_VALIDATION_RULE VR
 JOIN CNT_VALIDATION_PROFILE VP
 ON VR.PROFILE_ID = VP.ID WHERE VP.REF_ENTITY_NAME = 'Rfq' AND VP.REF_ENTITY_VERSION = 1 AND VP.DOMAIN_ID = '/' )
 AND VR.PROFILE_ID IN
 (SELECT VP.ID FROM CNT_VALIDATION_PROFILE VP
 WHERE VP.REF_ENTITY_NAME = 'Rfq' AND VP.REF_ENTITY_VERSION = 1 AND VP.ACTION = 'RfqSend' AND VP.DOMAIN_ID = '/');

-- #4 add CNT_VALIDATION_FIELD_PARAM for RfqSend action.
 INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
 SELECT LOWER(SYS_GUID()), 0, 1, '/', CVF.ID AS VALIDATION_FIELD_ID, 'LABEL_FIELD_ID', 'rfqItem' 
 FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR,CNT_VALIDATION_PROFILE CVP
 WHERE CVR.PROFILE_ID = CVP.ID  AND CVR.domain_id = '/' AND CVF.VALIDATION_RULE_ID = CVR.ID
 AND CVP.ACTION = 'RfqSend'AND CVP.domain_id = '/' AND CVF.REF_ENTITY_NAME = 'Rfq' 
 AND CVF.DOMAIN_ID = '/' AND CVF.FIELD_ID = 'rfqItem';

 INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
 SELECT LOWER(SYS_GUID()), 0, 1, '/', CVF.ID AS VALIDATION_FIELD_ID, 'LABEL_FIELD_ID', 'rfqVendor' 
 FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR, CNT_VALIDATION_PROFILE CVP
 WHERE CVR.PROFILE_ID = CVP.ID  AND CVR.domain_id = '/' AND CVF.VALIDATION_RULE_ID = CVR.ID 
 AND CVP.ACTION = 'RfqSend'AND CVP.domain_id = '/' AND CVF.REF_ENTITY_NAME = 'Rfq' 
 AND CVF.DOMAIN_ID = '/' AND CVF.FIELD_ID = 'rfqVendor';

 INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
 SELECT LOWER(SYS_GUID()), 0, 1, '/', CVF.ID AS VALIDATION_FIELD_ID, 'LABEL_FIELD_ID', 'expiryDate' 
 FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR, CNT_VALIDATION_PROFILE CVP 
 WHERE CVR.PROFILE_ID = CVP.ID  AND CVR.domain_id = '/' AND CVF.VALIDATION_RULE_ID = CVR.ID 
 AND CVP.ACTION = 'RfqSend'AND CVP.domain_id = '/' AND CVF.REF_ENTITY_NAME = 'Rfq' 
 AND CVF.DOMAIN_ID = '/' AND CVF.FIELD_ID = 'expiryDate';

 INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
 SELECT LOWER(SYS_GUID()), 0, 1, '/', CVF.ID AS VALIDATION_FIELD_ID, 'LABEL_FIELD_ID', 'email' 
 FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR, CNT_VALIDATION_PROFILE CVP
 WHERE CVR.PROFILE_ID = CVP.ID  AND CVR.domain_id = '/' AND CVF.VALIDATION_RULE_ID = CVR.ID 
 AND CVP.ACTION = 'RfqSend'AND CVP.domain_id = '/' AND CVF.REF_ENTITY_NAME = 'RfqVendor' 
 AND CVF.DOMAIN_ID = '/' AND CVF.FIELD_ID = 'email';

 INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
 SELECT LOWER(SYS_GUID()), 0, 1, '/', CVF.ID AS VALIDATION_FIELD_ID, 'GRID_ID', 'rfqVendor' 
 FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR, CNT_VALIDATION_PROFILE CVP
 WHERE CVR.PROFILE_ID = CVP.ID  AND CVR.domain_id = '/'AND CVF.VALIDATION_RULE_ID = CVR.ID 
 AND CVP.ACTION = 'RfqSend'AND CVP.domain_id = '/' AND CVF.REF_ENTITY_NAME = 'RfqVendor' 
 AND CVF.DOMAIN_ID = '/' AND CVF.FIELD_ID = 'email';

-- delete rfqItem and rfqVendor validation when 'save' action. 
 DELETE FROM CNT_VALIDATION_FIELD_PARAM CVFP WHERE CVFP.VALIDATION_FIELD_ID in
 (SELECT CVF.ID FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR, CNT_VALIDATION_PROFILE CVP
 WHERE CVR.PROFILE_ID = CVP.ID And CVR.domain_id = '/' AND CVF.VALIDATION_RULE_ID = CVR.ID
 And CVF.domain_id = '/' AND CVP.REF_ENTITY_NAME = 'Rfq' And CVP.domain_id = '/' 
 AND CVP.ACTION = 'SaveDoc,ConfirmDoc,SaveAndConfirm' AND CVF.FIELD_ID in ('rfqVendor') );

 DELETE FROM CNT_VALIDATION_FIELD CVF WHERE CVF.ID in 
 (SELECT CVF.ID FROM CNT_VALIDATION_FIELD CVF, CNT_VALIDATION_RULE CVR, CNT_VALIDATION_PROFILE CVP
 WHERE CVR.PROFILE_ID = CVP.ID AND CVR.domain_id = '/' AND CVF.VALIDATION_RULE_ID = CVR.ID
 AND CVF.domain_id = '/' AND CVP.REF_ENTITY_NAME = 'Rfq' AND CVP.domain_id = '/' 
 AND CVP.ACTION = 'SaveDoc,ConfirmDoc,SaveAndConfirm' AND CVF.FIELD_ID in ('rfqVendor'));

--CNT-4432 CPM Validation 
INSERT INTO CNT_VALIDATION_RULE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME,  ENABLED) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, p.ID, MAX(LINE_NO) + 1, 'ExpressionValidator', 'com.core.cbx.validation.validator.ExpressionValidator', 1 FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r on r.PROFILE_ID=p.ID  WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND NOT EXISTS (SELECT 1 FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON r.PROFILE_ID=p.ID WHERE r.DOMAIN_ID='/' AND r.RULE_TYPE='ExpressionValidator' AND p.REF_ENTITY_NAME='CpmTask') GROUP BY p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, p.ID;
INSERT INTO CNT_VALIDATION_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, r.ID, 1, 'CpmTask', 'planEnd', 'entity.planEnd', 1 FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1);
INSERT INTO CNT_VALIDATION_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, r.ID, 3, 'CpmTask', 'actualEnd', 'entity.actualEnd', 1 FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=3);
INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, f.ID, 'EXPRESSION', 'entity.planEnd > entity.planStart||entity.planEnd = entity.planStart' FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID LEFT JOIN CNT_VALIDATION_FIELD_PARAM fp ON fp.VALIDATION_FIELD_ID=f.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND fp.PARAM_KEY='EXPRESSION');
INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, f.ID, 'ERROR_ID', '08010006' FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID LEFT JOIN CNT_VALIDATION_FIELD_PARAM fp ON fp.VALIDATION_FIELD_ID=f.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND fp.PARAM_KEY='ERROR_ID');
INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, f.ID, 'EXPRESSION', 'entity.actualEnd > entity.actualStart||entity.actualEnd = entity.actualStart' FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=3 AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID LEFT JOIN CNT_VALIDATION_FIELD_PARAM fp ON fp.VALIDATION_FIELD_ID=f.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=3 AND fp.PARAM_KEY='EXPRESSION');
INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, f.ID, 'ERROR_ID', '08010008' FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=3 AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID LEFT JOIN CNT_VALIDATION_FIELD_PARAM fp ON fp.VALIDATION_FIELD_ID=f.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='CpmTask' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=3 AND fp.PARAM_KEY='ERROR_ID');
--END of CNT-4432 CPM Validation 

-- Remove custom field rules  BEGIN **-----------------------
DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE VALIDATION_FIELD_ID in (select id FROM CNT_VALIDATION_FIELD WHERE field_id like 'custText%' or field_id like 'custNumber%' or field_id like 'custDate%');
DELETE FROM CNT_VALIDATION_FIELD WHERE field_id like 'custText%' or field_id like 'custNumber%' or field_id like 'custDate%';
-- Remove custom field rules ENG-----------------------


--CNT-5220
-- 1 CNT_VALIDATION_PROFILE
update cnt_validation_profile set action ='SaveDoc,ConfirmDoc,SaveAndConfirm,PopupUserPreferenceOkAction'
where id =(select id from cnt_validation_profile where ref_entity_name ='User' and domain_id ='/' and action='SaveDoc,ConfirmDoc,SaveAndConfirm');

--2 CNT_VALIDATION_RULE
INSERT INTO CNT_VALIDATION_RULE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME,  ENABLED) 
SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, p.ID, MAX(LINE_NO) + 1, 'ExpressionValidator', 'com.core.cbx.validation.validator.ExpressionValidator', 1 
FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r on r.PROFILE_ID=p.ID  
WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND NOT EXISTS 
(SELECT 1 FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON r.PROFILE_ID=p.ID WHERE r.DOMAIN_ID='/' AND r.RULE_TYPE='ExpressionValidator' 
AND p.REF_ENTITY_NAME='User') GROUP BY p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, p.ID;

-- 3 CNT_VALIDATION_FIELD
INSERT INTO CNT_VALIDATION_FIELD (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, r.ID, 1, 'User', 'password', 'entity.password', 1 FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND r.RULE_TYPE='ExpressionValidator' AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1);

-- 4 CNT_VALIDATION_FIELD_PARAM
INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE) SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, f.ID, 'EXPRESSION', 'entity.password = entity.confirmPassword' FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID LEFT JOIN CNT_VALIDATION_FIELD_PARAM fp ON fp.VALIDATION_FIELD_ID=f.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND fp.PARAM_KEY='EXPRESSION');
INSERT INTO CNT_VALIDATION_FIELD_PARAM (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE) 
SELECT LOWER(SYS_GUID()), p.REVISION, p.ENTITY_VERSION, p.DOMAIN_ID, f.ID, 'ERROR_ID', '02013005' FROM CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND NOT EXISTS(SELECT 1 FROM  CNT_VALIDATION_PROFILE p LEFT JOIN CNT_VALIDATION_RULE r ON p.ID=r.PROFILE_ID LEFT JOIN CNT_VALIDATION_FIELD f ON f.VALIDATION_RULE_ID=r.ID LEFT JOIN CNT_VALIDATION_FIELD_PARAM fp ON fp.VALIDATION_FIELD_ID=f.ID WHERE p.DOMAIN_ID='/' AND p.REF_ENTITY_NAME='User' AND r.RULE_TYPE='ExpressionValidator' AND f.LINE_NO=1 AND fp.PARAM_KEY='ERROR_ID');
--End OF CNT-5220

--CNT-5429 CpmTempl VALIDATION
----insert mandatoryValidator for CpmTempl.anchorDateFieldId--------------- 

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID =(SELECT ID FROM CNT_CONDITION WHERE NAME = 'cpmTemplDynamicType' AND DOMAIN_ID = '/') 
WHERE FIELD_ID = 'anchorDateFieldId' AND  REF_ENTITY_NAME = 'CpmTempl' AND DOMAIN_ID = '/';

----insert mandatoryValidator for CpmTempl.CpmTemplTask.planStart---------------

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID =(SELECT ID FROM CNT_CONDITION WHERE NAME = 'cpmTemplStaticType' AND DOMAIN_ID = '/') 
WHERE FIELD_ID = 'planStart' AND  REF_ENTITY_NAME = 'CpmTemplTask' AND DOMAIN_ID = '/';

----insert mandatoryValidator for CpmTempl.CpmTemplTask.planEnd--------------

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID =(SELECT ID FROM CNT_CONDITION WHERE NAME = 'cpmTemplStaticType' AND DOMAIN_ID = '/') 
WHERE FIELD_ID = 'planEnd' AND  REF_ENTITY_NAME = 'CpmTemplTask' AND DOMAIN_ID = '/';

----insert mandatoryValidator for CpmTempl.CpmTemplTask.offset----------

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID =(SELECT ID FROM CNT_CONDITION WHERE NAME = 'cpmTemplStaticType' AND DOMAIN_ID = '/') 
WHERE FIELD_ID = 'offset' AND  REF_ENTITY_NAME = 'CpmTemplTask' AND DOMAIN_ID = '/';

----insert mandatoryValidator for CpmTempl.CpmTemplTask.duration

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID =(SELECT ID FROM CNT_CONDITION WHERE NAME = 'cpmTemplStaticType' AND DOMAIN_ID = '/') 
WHERE FIELD_ID = 'duration' AND  REF_ENTITY_NAME = 'CpmTemplTask' AND DOMAIN_ID = '/';

--End OF CNT-5429

--CNT-5702 CpmTempl VALIDATION
UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID = (
SELECT ID FROM CNT_CONDITION WHERE EXPRESSION = 'entity.cpmTemplType=2' AND DOMAIN_ID = '/'
) WHERE FIELD_PATH IN ('entity.cpmTemplTasks.offset','entity.cpmTemplTasks.duration') AND DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'CpmTemplTask';

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID = (
SELECT ID FROM CNT_CONDITION WHERE EXPRESSION = 'entity.cpmTemplType=2' AND DOMAIN_ID = '/'
) WHERE FIELD_PATH IN ('entity.anchorDateFieldId') AND DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'CpmTempl';
--End OF CNT-5702

----CNT-5188 BEGIN--
-----insert mandatoryValidator for CustFieldDef.tabId and CustFieldDef.tableId
INSERT INTO CNT_VALIDATION_FIELD
 (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, LINE_NO, ENABLED)
VALUES (LOWER(SYS_GUID()), 0, 1, '/', (SELECT VR.ID FROM CNT_VALIDATION_RULE VR JOIN CNT_VALIDATION_PROFILE VP ON VR.PROFILE_ID = VP.ID WHERE VP.REF_ENTITY_NAME = 'CustFieldDef' AND VR.RULE_TYPE = 'MandatoryValidator' AND VR.DOMAIN_ID = '/'), 'CustFieldDef', 'tabId', 'entity.tabId', 5, 1);

INSERT INTO CNT_VALIDATION_FIELD
 (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, LINE_NO, ENABLED)
VALUES (LOWER(SYS_GUID()), 0, 1, '/', (SELECT VR.ID FROM CNT_VALIDATION_RULE VR JOIN CNT_VALIDATION_PROFILE VP ON VR.PROFILE_ID = VP.ID WHERE VP.REF_ENTITY_NAME = 'CustFieldDef' AND VR.RULE_TYPE = 'MandatoryValidator' AND VR.DOMAIN_ID = '/'), 'CustFieldDef', 'tableId', 'entity.tableId', 6, 1);

INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'tabId' FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'CustFieldDef' AND ACTION = 'SaveDoc,ConfirmDoc,SaveAndConfirm') )
AND FIELD_PATH = 'entity.tabId' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'tableId' FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'CustFieldDef' AND ACTION = 'SaveDoc,ConfirmDoc,SaveAndConfirm') )
AND FIELD_PATH = 'entity.tableId' AND DOMAIN_ID = '/';


-----add condition id into the mandatory field for CustFieldDef.tabId and CustFieldDef.tableId
UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID=(SELECT ID FROM CNT_CONDITION WHERE NAME='isTab' AND DOMAIN_ID='/') WHERE FIELD_ID='tabId' AND DOMAIN_ID='/';

UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID=(SELECT ID FROM CNT_CONDITION WHERE NAME='isTable' AND DOMAIN_ID='/') WHERE FIELD_ID='tableId' AND DOMAIN_ID='/';

----CNT-5188 END--

--*************CNT-4625 root domain validation.***********
DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE DOMAIN_ID = '/' AND VALIDATION_FIELD_ID IN (SELECT ID FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk')));
DELETE FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID IN (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk'));
DELETE FROM CNT_VALIDATION_RULE WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk');
DELETE FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_PROFILE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, CREATED_ON, PROFILE_NAME, REF_ENTITY_NAME, REF_ENTITY_VERSION, ENABLED, ACTION)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', 'system', SYSDATE, 'Default Data Validation Profile Trigger[ver:1]', 'Trigger', 1, 1, 'PopDefActionPerformOk'
FROM DUAL;
  
  
INSERT INTO CNT_VALIDATION_RULE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk'
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'eventModule', 'entity.listeners.eventModule', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'eventModule'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk') )
AND FIELD_PATH = 'entity.listeners.eventModule' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'actionId', 'entity.listeners.actionId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'actionId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefActionPerformOk') )
AND FIELD_PATH = 'entity.listeners.actionId' AND DOMAIN_ID = '/';

DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE DOMAIN_ID = '/' AND VALIDATION_FIELD_ID IN (SELECT ID FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction')));
DELETE FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID IN (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction'));
DELETE FROM CNT_VALIDATION_RULE WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction');
DELETE FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_PROFILE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, CREATED_ON, PROFILE_NAME, REF_ENTITY_NAME, REF_ENTITY_VERSION, ENABLED, ACTION)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', 'system', SYSDATE, 'Default Data Validation Profile Trigger[ver:1]', 'Trigger', 1, 1, 'PopDeFieldChangeOkAction'
FROM DUAL;
  
  
INSERT INTO CNT_VALIDATION_RULE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction'
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'eventModule', 'entity.listeners.eventModule', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'eventModule'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.eventModule' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'requireType', 'entity.listeners.requireType', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'requireType'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.requireType' AND DOMAIN_ID = '/';

-- grid field 1
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'sourceId', 'entity.listeners.criterias.sourceId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'sourceId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';

-- grid field 2
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'fromValue', 'entity.listeners.criterias.fromValue', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'fromValue'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.fromValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.fromValue' AND DOMAIN_ID = '/';

-- grid field 2
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'toValue', 'entity.listeners.criterias.toValue', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'toValue'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.toValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDeFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.toValue' AND DOMAIN_ID = '/';

DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE DOMAIN_ID = '/' AND VALIDATION_FIELD_ID IN (SELECT ID FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')));
DELETE FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID IN (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction'));
DELETE FROM CNT_VALIDATION_RULE WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction');
DELETE FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_PROFILE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, CREATED_ON, PROFILE_NAME, REF_ENTITY_NAME, REF_ENTITY_VERSION, ENABLED, ACTION)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', 'system', SYSDATE, 'Default Data Validation Profile Trigger[ver:1]', 'Trigger', 1, 1, 'PopDefAprvFieldChangeOkAction'
FROM DUAL;
  
  
INSERT INTO CNT_VALIDATION_RULE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction'
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'aprvTmplId', 'entity.listeners.aprvTmplId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'aprvTmplId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.aprvTmplId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'requireType', 'entity.listeners.requireType', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'requireType'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.requireType' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'sourceGroupId', 'entity.listeners.criterias.sourceGroupId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'sourceGroupId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceGroupId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'sourceId', 'entity.listeners.criterias.sourceId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'sourceId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'fromValue', 'entity.listeners.criterias.fromValue', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'fromValue'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.fromValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.fromValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'toValue', 'entity.listeners.criterias.toValue', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'toValue'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.toValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefAprvFieldChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.toValue' AND DOMAIN_ID = '/';

DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE DOMAIN_ID = '/' AND VALIDATION_FIELD_ID IN (SELECT ID FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')));
DELETE FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID IN (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction'));
DELETE FROM CNT_VALIDATION_RULE WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction');
DELETE FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_PROFILE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, CREATED_ON, PROFILE_NAME, REF_ENTITY_NAME, REF_ENTITY_VERSION, ENABLED, ACTION)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', 'system', SYSDATE, 'Default Data Validation Profile Trigger[ver:1]', 'Trigger', 1, 1, 'PopDefCpmChangeOkAction'
FROM DUAL;
  
  
INSERT INTO CNT_VALIDATION_RULE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction'
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'cpmTmplId', 'entity.listeners.cpmTmplId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'cpmTmplId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.cpmTmplId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'requireType', 'entity.listeners.requireType', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'requireType'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.requireType' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'sourceGroupId', 'entity.listeners.criterias.sourceGroupId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'sourceGroupId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceGroupId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'sourceId', 'entity.listeners.criterias.sourceId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'sourceId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.sourceId' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'fromValue', 'entity.listeners.criterias.fromValue', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'fromValue'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.fromValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.fromValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT 
    LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListenerCriteria', 'toValue', 'entity.listeners.criterias.toValue', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
    LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'toValue'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.toValue' AND DOMAIN_ID = '/';


INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/',ID, 'GRID_ID', 'criterias'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopDefCpmChangeOkAction') )
AND FIELD_PATH = 'entity.listeners.criterias.toValue' AND DOMAIN_ID = '/';

DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE DOMAIN_ID = '/' AND VALIDATION_FIELD_ID IN (SELECT ID FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction')));
DELETE FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID IN (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction'));
DELETE FROM CNT_VALIDATION_RULE WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction');
DELETE FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_PROFILE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, CREATED_ON, PROFILE_NAME, REF_ENTITY_NAME, REF_ENTITY_VERSION, ENABLED, ACTION)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', 'system', SYSDATE, 'Default Data Validation Profile Trigger[ver:1]', 'Trigger', 1, 1, 'PopCpmTaskUpdateOkAction'
FROM DUAL;
  
  
INSERT INTO CNT_VALIDATION_RULE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction'
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'cpmTemplateId', 'entity.actions.cpmTemplateId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'cpmTemplateId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction') )
AND FIELD_PATH = 'entity.actions.cpmTemplateId' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'cpmTaskTemplateId', 'entity.actions.cpmTaskTemplateId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'cpmTaskTemplateId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction') )
AND FIELD_PATH = 'entity.actions.cpmTaskTemplateId' AND DOMAIN_ID = '/';

-- need condition
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'rejectReasonId', 'entity.actions.rejectReasonId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'rejectReasonId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction') )
AND FIELD_PATH = 'entity.actions.rejectReasonId' AND DOMAIN_ID = '/';

-- 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'rejectDescription', 'entity.actions.rejectDescription', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'rejectDescription'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction') )
AND FIELD_PATH = 'entity.actions.rejectDescription' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'deferDays', 'entity.actions.deferDays', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'deferDays'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopCpmTaskUpdateOkAction') )
AND FIELD_PATH = 'entity.actions.deferDays' AND DOMAIN_ID = '/';


DELETE FROM CNT_VALIDATION_FIELD_PARAM WHERE DOMAIN_ID = '/' AND VALIDATION_FIELD_ID IN (SELECT ID FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction')));
DELETE FROM CNT_VALIDATION_FIELD WHERE DOMAIN_ID = '/' AND VALIDATION_RULE_ID IN (SELECT ID FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction'));
DELETE FROM CNT_VALIDATION_RULE WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction');
DELETE FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction' AND DOMAIN_ID = '/';

INSERT INTO CNT_VALIDATION_PROFILE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, CREATED_ON, PROFILE_NAME, REF_ENTITY_NAME, REF_ENTITY_VERSION, ENABLED, ACTION)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', 'system', SYSDATE, 'Default Data Validation Profile Trigger[ver:1]', 'Trigger', 1, 1, 'PopSendNotificationOkAction'
FROM DUAL;
  
  
INSERT INTO CNT_VALIDATION_RULE
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, LINE_NO, RULE_TYPE, VALIDATOR_CLASS_NAME, ENABLED)
SELECT 
   LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'MandatoryValidator', 'com.core.cbx.validation.validator.MandatoryValidator', 1
FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction'
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_RULE_ID, LINE_NO, REF_ENTITY_NAME, FIELD_ID, FIELD_PATH, ENABLED)
SELECT
  LOWER(SYS_GUID()), 0, 1, '/', ID, 1, 'TriggerListener', 'notificationId', 'entity.actions.notificationId', 1
FROM CNT_VALIDATION_RULE  WHERE PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE DOMAIN_ID = '/' AND REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction')
AND DOMAIN_ID = '/';

 
INSERT INTO CNT_VALIDATION_FIELD_PARAM
   (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VALIDATION_FIELD_ID, PARAM_KEY, PARAM_VALUE)
SELECT
   LOWER(SYS_GUID()), 0, 1, '/', ID, 'LABEL_FIELD_ID', 'notificationId'
FROM CNT_VALIDATION_FIELD WHERE VALIDATION_RULE_ID = (SELECT ID FROM CNT_VALIDATION_RULE  WHERE DOMAIN_ID = '/' AND PROFILE_ID IN (SELECT ID FROM CNT_VALIDATION_PROFILE WHERE REF_ENTITY_NAME = 'Trigger' AND ACTION = 'PopSendNotificationOkAction') )
AND FIELD_PATH = 'entity.actions.notificationId' AND DOMAIN_ID = '/';

-- SET UP SOME FIELDS CONDITION.
UPDATE CNT_VALIDATION_FIELD SET CONDITION_ID = (SELECT ID FROM CNT_CONDITION WHERE NAME = 'validateCpmTaskStatus' AND DOMAIN_ID = '/') 
		WHERE FIELD_PATH IN ('entity.actions.deferDays', 'entity.actions.rejectDescription', 'entity.actions.rejectReasonId') AND DOMAIN_ID = '/';
		
--*************CNT-4625 root domain validation.***********