WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK
SET DEFINE OFF

--CNT-11183 BEGIN---
INSERT INTO CNT_DATA_LIST_TYPE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER,UPDATE_USER,CREATED_ON, UPDATED_ON, NAME,APPLY_TO_ENTITY,HUB_DOMAIN_ID, IS_FOR_REFERENCE,IS_LATEST)
SELECT LOWER(SYS_GUID()), 1, 1, book.domain_id, 1, 'system','system',sysdate,sysdate,book.name, 2 ,book.hub_domain_id, 0,1 FROM cnt_codelist_book book
WHERE book.TYPE_ID is null and not exists (select 1 from CNT_DATA_LIST_TYPE type where type.name=book.name and type.domain_id = book.domain_id);


update cnt_codelist_book book set type_id = (select id from cnt_data_list_type type where type.name=book.name and type.domain_id = book.domain_id) WHERE BOOK.TYPE_ID IS NULL;
--CNT-11183 END---


--CNT-11293 BEGIN---
INSERT INTO CNT_DEFAULT_PROFILE (
 ID, REVISION, ENTITY_VERSION, DOC_STATUS, EDITING_STATUS, CREATE_USER, CREATED_ON,
 REF_ENTITY_NAME, REF_NO,
 HUB_DOMAIN_ID, IS_FOR_REFERENCE, IS_LATEST, CREATE_USER_NAME, DOMAIN_ID)
 SELECT SYS_GUID(), 1, 1, 'active', 'confirmed', 'system', SYSDATE, 
    'NotificationProfile', (select 'S13-' || lpad(next_val, 6, '0') from CNT_SEQ_DEF where seq_id = 'CBX_SEQ_DEFAULT_PROFILE_REF_NO' and domain_id = '/'), '/', 0, 1, 'system', '/' 
 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1);
 

INSERT INTO CNT_DEFAULT_PROFILE_FIELD ( ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, 
 MASTER_SEQ_NO, 
 SEQ_NO, FIELD_ID, VALUE_TYPE, DEFAULT_VALUE, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1), 
   (SELECT nvl(MAX(MASTER_SEQ_NO)+1,1) FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)), 
   (SELECT nvl(MAX(SEQ_NO)+1,1) FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)), 'inboxEnabled', 'fixed', 'true', '/', 0 
 FROM DUAL WHERE NOT EXISTS ( 
   SELECT 1 FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1) AND DOMAIN_ID = '/');



INSERT INTO CNT_CODELIST_LINK_INFO(ID, REVISION, ENTITY_VERSION, DOMAIN_ID, REF_ID, REF_ENTITY, REF_FIELD, CODELIST_DOMAIN, 
  CODELIST_NAME, CODELIST_VERSION, CODELIST_CODE, CREATE_USER, CREATED_ON, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)), 
 'DefaultProfileField', 'valueType', '/', 'DEFAULT_VALUE_TYPE', 1, 'fixed', 'system', SYSDATE, '/', 0
 FROM DUAL WHERE NOT EXISTS 
(SELECT 1 FROM CNT_CODELIST_LINK_INFO WHERE REF_ENTITY = 'DefaultProfileField' AND REF_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)) AND DOMAIN_ID = '/');



UPDATE CNT_NOTIFICATION_PROFILE SET INBOX_ENABLED = 1 WHERE IS_LATEST = 1;
--CNT-11293 END---



--CNT-11322 BEGIN----------------------------------------------
UPDATE cnt_view_action
SET action_params = action_params || '&upload=true&listener=com.core.cbx.ui.listener.ImportRawDataListener'
WHERE action_name = 'importRawData'
AND InStr(action_params, '&upload=true&listener=com.core.cbx.ui.listener.ImportRawDataListener') = 0;
--CNT-11322 END----------------------------------------------



--CNT-11097 BEGIN----------------------------------------------
--------project----------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'program', (SELECT ID FROM CNT_VIEW WHERE NAME = 'projectItemView' AND MODULE_ID = 'project' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'program'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'program' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'projectItemView' AND MODULE_ID = 'project' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


--------mpo----------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'item'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'item' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'spec', (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'spec'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'spec' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vq', (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vq'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vq' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'cust', (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'cust'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'cust' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendor', (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoQtyItemView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoActiveView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'mpoActiveView' AND MODULE_ID = 'mpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

--------vq----------------------------------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vqActiveView' AND MODULE_ID = 'vq' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vqActiveView' AND MODULE_ID = 'vq' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'mpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vqActiveView' AND MODULE_ID = 'vq' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'mpo'), 1,  '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'mpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vqActiveView' AND MODULE_ID = 'vq' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


--------vpo-------------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendorInvoice', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoActiveView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoActiveView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');
 
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vq', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoQtyItemView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vq'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vq' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoQtyItemView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'offersheet', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoQtyItemView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'offersheet'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'offersheet' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoQtyItemView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'mpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoQtyItemView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'mpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'mpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoQtyItemView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'letterOfCredit', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoActiveView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'letterOfCredit'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'letterOfCredit' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vpoActiveView' AND MODULE_ID = 'vpo' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');
 

-------vendor------------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'claim', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorActiveView' AND MODULE_ID = 'vendor' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'claim'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'claim' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorActiveView' AND MODULE_ID = 'vendor' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');
 
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendorInvoice', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorActiveView' AND MODULE_ID = 'vendor' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorActiveView' AND MODULE_ID = 'vendor' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');
 

 ----------vendorInv-----------------------------------
 INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'item', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorInvoiceQtyByItemView' AND MODULE_ID = 'vendorInvoice' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'item'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'item' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorInvoiceQtyByItemView' AND MODULE_ID = 'vendorInvoice' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorInvoiceQtyByItemView' AND MODULE_ID = 'vendorInvoice' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorInvoiceQtyByItemView' AND MODULE_ID = 'vendorInvoice' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendor', (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorInvoiceActiveView' AND MODULE_ID = 'vendorInvoice' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'vendorInvoiceActiveView' AND MODULE_ID = 'vendorInvoice' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


--------OS-------------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'offerSheetsItemsView' AND MODULE_ID = 'offersheet' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'offerSheetsItemsView' AND MODULE_ID = 'offersheet' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


--------letterOfCredit----------------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME) 
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'letterOfCreditAmtByOrderView' AND MODULE_ID = 'letterOfCredit' AND DOMAIN_ID = '/'), 
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'letterOfCreditAmtByOrderView' AND MODULE_ID = 'letterOfCredit' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


---------cust-------------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'claim', (SELECT ID FROM CNT_VIEW WHERE NAME = 'custActiveView' AND MODULE_ID = 'cust' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'claim'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'claim' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'custActiveView' AND MODULE_ID = 'cust' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


---------item-------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendorInvoice', (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemActiveView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemActiveView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'mpo', (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemActiveView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'mpo'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'mpo' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'itemActiveView' AND MODULE_ID = 'item' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


----------custInv-------------------------------------
INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendorInvoice', (SELECT ID FROM CNT_VIEW WHERE NAME = 'custInvActiveView' AND MODULE_ID = 'custInv' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendorInvoice' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'custInvActiveView' AND MODULE_ID = 'custInv' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');


--------claim-------------------------------------
 INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'cust', (SELECT ID FROM CNT_VIEW WHERE NAME = 'claimActiveView' AND MODULE_ID = 'claim' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'cust'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'cust' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'claimActiveView' AND MODULE_ID = 'claim' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

INSERT INTO CNT_RELATED_DOC_PROFILE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, 
MODULE, VIEW_ID, DISABLED, SEQUENCE, IS_DEFAULT, HUB_DOMAIN_ID, IS_FOR_REFERENCE, CREATE_USER_NAME, UPDATE_USER_NAME)
 SELECT SYS_GUID(), 1, 1, '/', 1, 'system', 'system', sysdate, sysdate, 'vendor', (SELECT ID FROM CNT_VIEW WHERE NAME = 'claimActiveView' AND MODULE_ID = 'claim' AND DOMAIN_ID = '/'),
0, (SELECT MAX(SEQUENCE) + 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor'), 1, '/', 0, 'system', 'system' FROM DUAL WHERE NOT EXISTS (
 SELECT 1 FROM CNT_RELATED_DOC_PROFILE WHERE MODULE = 'vendor' AND VIEW_ID = (SELECT ID FROM CNT_VIEW WHERE NAME = 'claimActiveView' AND MODULE_ID = 'claim' AND DOMAIN_ID = '/') AND DOMAIN_ID = '/');

--CNT-11097 END----------------------------------------------



COMMIT;   