WHENEVER SQLERROR EXIT sql.sqlcode ROLLBACK
SET DEFINE OFF

--CNT-11183 BEGIN---
INSERT INTO CNT_DATA_LIST_TYPE (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, VERSION, CREATE_USER,UPDATE_USER,CREATED_ON, UPDATED_ON, NAME,APPLY_TO_ENTITY,HUB_DOMAIN_ID, IS_FOR_REFERENCE,IS_LATEST)
SELECT LOWER(SYS_GUID()), 1, 1, book.domain_id, 1, 'system','system',sysdate,sysdate,book.name, 2 ,book.hub_domain_id, 0,1 FROM cnt_codelist_book book
WHERE book.TYPE_ID is null and not exists (select 1 from CNT_DATA_LIST_TYPE type where type.name=book.name and type.domain_id = book.domain_id);


update cnt_codelist_book book set type_id = (select id from cnt_data_list_type type where type.name=book.name and type.domain_id = book.domain_id) WHERE BOOK.TYPE_ID IS NULL;
--CNT-11183 END---


--CNT-11293 BEGIN---
INSERT INTO CNT_DEFAULT_PROFILE (
 ID, REVISION, ENTITY_VERSION, DOC_STATUS, EDITING_STATUS, CREATE_USER, CREATED_ON,
 REF_ENTITY_NAME, REF_NO,
 HUB_DOMAIN_ID, IS_FOR_REFERENCE, IS_LATEST, CREATE_USER_NAME, DOMAIN_ID)
 SELECT SYS_GUID(), 1, 1, 'active', 'confirmed', 'system', SYSDATE, 
    'NotificationProfile', (select 'S13-' || lpad(next_val, 6, '0') from CNT_SEQ_DEF where seq_id = 'CBX_SEQ_DEFAULT_PROFILE_REF_NO' and domain_id = '/'), '/', 0, 1, 'system', '/' 
 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1);
 

INSERT INTO CNT_DEFAULT_PROFILE_FIELD ( ID, REVISION, ENTITY_VERSION, DOMAIN_ID, PROFILE_ID, 
 MASTER_SEQ_NO, 
 SEQ_NO, FIELD_ID, VALUE_TYPE, DEFAULT_VALUE, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1), 
   (SELECT nvl(MAX(MASTER_SEQ_NO)+1,1) FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)), 
   (SELECT nvl(MAX(SEQ_NO)+1,1) FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)), 'inboxEnabled', 'fixed', 'true', '/', 0 
 FROM DUAL WHERE NOT EXISTS ( 
   SELECT 1 FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1) AND DOMAIN_ID = '/');



INSERT INTO CNT_CODELIST_LINK_INFO(ID, REVISION, ENTITY_VERSION, DOMAIN_ID, REF_ID, REF_ENTITY, REF_FIELD, CODELIST_DOMAIN, 
  CODELIST_NAME, CODELIST_VERSION, CODELIST_CODE, CREATE_USER, CREATED_ON, HUB_DOMAIN_ID, IS_FOR_REFERENCE)
 SELECT SYS_GUID(), 1, 1, '/', (SELECT ID FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)), 
 'DefaultProfileField', 'valueType', '/', 'DEFAULT_VALUE_TYPE', 1, 'fixed', 'system', SYSDATE, '/', 0
 FROM DUAL WHERE NOT EXISTS 
(SELECT 1 FROM CNT_CODELIST_LINK_INFO WHERE REF_ENTITY = 'DefaultProfileField' AND REF_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE_FIELD WHERE FIELD_ID = 'inboxEnabled' AND PROFILE_ID = (SELECT ID FROM CNT_DEFAULT_PROFILE WHERE REF_ENTITY_NAME = 'NotificationProfile' AND DOMAIN_ID = '/' AND IS_LATEST = 1)) AND DOMAIN_ID = '/');



UPDATE CNT_NOTIFICATION_PROFILE SET INBOX_ENABLED = 1 WHERE IS_LATEST = 1;
--CNT-11293 END---

COMMIT;   