DROP SEQUENCE	CBX_SEQ_FACT_CODE	;
DROP SEQUENCE	CBX_SEQ_CUST_CODE	;
DROP SEQUENCE	CBX_SEQ_VENDOR_CODE	;
DROP SEQUENCE	CBX_SEQ_CPO_CPO_NO	;
DROP SEQUENCE	CBX_SEQ_VPO_VPO_NO	;
DROP SEQUENCE	CBX_SEQ_MPO_MPO_NO	;
DROP SEQUENCE	CBX_SEQ_OFFER_SHEET_NO	;
DROP SEQUENCE	CBX_SEQ_COMMITMENT_NO	;
DROP SEQUENCE	CBX_SEQ_RFQ_NO	;
DROP SEQUENCE	CBX_SEQ_VQ_NO	;
DROP SEQUENCE	CBX_SEQ_BRIEF_CODE	;
DROP SEQUENCE	CBX_SEQ_FACT_AUDIT_CODE	;
DROP SEQUENCE	CBX_SEQ_IC_CODE	;
DROP SEQUENCE	CBX_SEQ_QC_CODE	;
DROP SEQUENCE	CBX_SEQ_CI_CODE	;
DROP SEQUENCE	CBX_SEQ_SHIP_CODE	;
DROP SEQUENCE	CBX_SEQ_CBX_SAMPLE_CODE	;
DROP SEQUENCE	CBX_SEQ_ITEM_CODE	;

CREATE SEQUENCE	CBX_SEQ_FACT_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_CUST_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 NOCYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_VENDOR_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 NOCYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_CPO_CPO_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_VPO_VPO_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_MPO_MPO_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_OFFER_SHEET_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_COMMITMENT_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_RFQ_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_VQ_NO	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_BRIEF_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_FACT_AUDIT_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_IC_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_QC_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_CI_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_SHIP_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_CBX_SAMPLE_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;
CREATE SEQUENCE	CBX_SEQ_ITEM_CODE	INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOORDER;


