CREATE OR REPLACE PROCEDURE SP_APPLY_USER_ROLE ( 
--IN PARAMETERS: DOMAIN ID, USER LOGIN ID, GROUP NAME
--THIS PROCEDURE WILL HELP YOU TO ADD THE USER TO THE RIGHT GROUP ACCORDING TO YOUR PARAMETERS
   IN_DOMAIN_ID VARCHAR2,
   IN_LOGIN_ID VARCHAR2,
   IN_ROLE_CODE VARCHAR2
)
AS 
V_TMP_COUNT NUMBER(10) :=0;
BEGIN 

SELECT COUNT(1) INTO V_TMP_COUNT FROM CNT_USER WHERE DOMAIN_ID = IN_DOMAIN_ID AND LOGIN_ID = IN_LOGIN_ID;

IF V_TMP_COUNT > 0 THEN 

        INSERT INTO CNT_MEMBER_ROLE (
          ID, REVISION, ENTITY_VERSION, DOMAIN_ID, ROLE_ID, MEMBER_ID, MEMBER_TYPE,  ACCESS_RIGHT)
        SELECT SYS_GUID(), 0, 1, IN_DOMAIN_ID, R.ID, U.ID, 1, 1
        FROM CNT_USER U, CNT_ROLE R
        WHERE U.LOGIN_ID = IN_LOGIN_ID AND U.DOMAIN_ID = IN_DOMAIN_ID
        AND R.NAME = IN_ROLE_CODE  AND R.DOMAIN_ID = IN_DOMAIN_ID
        AND NOT EXISTS (
          SELECT 1 FROM CNT_MEMBER_ROLE WHERE (ROLE_ID, MEMBER_ID, MEMBER_TYPE, DOMAIN_ID) IN (
            SELECT R.ID, U.ID, 1, IN_DOMAIN_ID
            FROM CNT_USER U, CNT_ROLE R
            WHERE U.LOGIN_ID = IN_LOGIN_ID AND U.DOMAIN_ID = IN_DOMAIN_ID
            AND R.NAME = IN_ROLE_CODE AND R.DOMAIN_ID = IN_DOMAIN_ID
          )
        );

ELSE
    INSERT INTO CNT_MEMBER_ROLE (
    ID, REVISION, ENTITY_VERSION, DOMAIN_ID, ROLE_ID, MEMBER_ID, MEMBER_TYPE,  ACCESS_RIGHT)
    SELECT SYS_GUID(), 0, 1, IN_DOMAIN_ID, RL.ID, GRP.ID, 2, 1
    FROM CNT_GROUP GRP, CNT_ROLE RL
    WHERE RL.NAME = IN_ROLE_CODE  AND RL.DOMAIN_ID = IN_DOMAIN_ID
    AND GRP.DOMAIN_ID = IN_DOMAIN_ID AND GRP.NAME = IN_LOGIN_ID
    AND NOT EXISTS (SELECT 1 FROM CNT_MEMBER_ROLE MBR
    WHERE MBR.ROLE_ID = RL.ID AND MBR.MEMBER_ID = GRP.ID AND MBR.DOMAIN_ID = GRP.DOMAIN_ID
    );

END IF;
    
EXCEPTION
   WHEN OTHERS
   THEN
   RAISE_APPLICATION_ERROR(-20001, SQLERRM); 
END;
/
