CREATE OR REPLACE PROCEDURE SP_INIT_ROLE_UI_TABLE(I_DOMAIN_ID IN VARCHAR2)
AS
    CURSOR C_RULE_ACTION IS SELECT DISTINCT ROLE_ID, ACCESS_OBJECT_ID, CONDITION_ID FROM CNT_RULE_ACTION WHERE DOMAIN_ID = I_DOMAIN_ID;
    GUID CHAR(32);
BEGIN
    
    DELETE FROM CNT_RULE_ACTION_ADMIN WHERE DOMAIN_ID = I_DOMAIN_ID;
    
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleActionAdmin' AND FIELD_ID='objectId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleActionAdmin' AND FIELD_ID='actionId' AND DOMAIN_ID = I_DOMAIN_ID;
    DELETE FROM CNT_SELECTION WHERE PARENT_ENTITY='RuleActionAdmin' AND FIELD_ID='conditionId' AND DOMAIN_ID = I_DOMAIN_ID; 
 
    FOR CUR IN C_RULE_ACTION
    LOOP
        GUID:=sys_guid();
        INSERT INTO CNT_RULE_ACTION_ADMIN (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, ROLE_ID)
            SELECT GUID, 1, 1, I_DOMAIN_ID, CUR.ROLE_ID FROM DUAL;
        INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
            SELECT sys_guid(), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleActionAdmin', 'objectId', 'AccessObject', CUR.ACCESS_OBJECT_ID FROM DUAL;
        INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
            SELECT sys_guid(), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleActionAdmin', 'conditionId', 'Condition', CUR.CONDITION_ID FROM DUAL;
        INSERT INTO CNT_SELECTION (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, CREATE_USER, UPDATE_USER, CREATED_ON, UPDATED_ON, PARENT_ID, PARENT_ENTITY, FIELD_ID, REF_ENTITY, REF_ID)
            SELECT sys_guid(), 1, 1, I_DOMAIN_ID, 'system', 'system', sysdate, sysdate, GUID, 'RuleActionAdmin', 'actionId', 'AccessObjectAction', AOA.ID FROM CNT_RULE_ACTION ACTION, CNT_ACCESS_OBJECT_ACTION AOA
                WHERE ACTION.ROLE_ID = CUR.ROLE_ID AND ACTION.ACCESS_OBJECT_ID = CUR.ACCESS_OBJECT_ID AND ACTION.CONDITION_ID = CUR.CONDITION_ID AND ACTION.DOMAIN_ID = I_DOMAIN_ID
                			AND CUR.ACCESS_OBJECT_ID = AOA.ACCESS_OBJECT_ID AND ACTION.ACTION_ID = AOA.ACTION_ID AND AOA.DOMAIN_ID = I_DOMAIN_ID;
    END LOOP;
 
END;
/