drop table  CNT_CPO_ITEM_COLOR  cascade constraints;
drop table  CNT_CPO_ITEM_CS  cascade constraints;
drop table  CNT_CPO_ITEM_SIZE  cascade constraints;
drop table  CNT_CPO_SHIP  cascade constraints;
drop table  CNT_CPO_SHIP_DC  cascade constraints;
drop table  CNT_CPO_SHIP_DTL  cascade constraints;
drop table  CNT_CPO_SHIP_DTL_COLOR  cascade constraints;
drop table  CNT_CPO_SHIP_DTL_CS  cascade constraints;
drop table  CNT_CPO_SHIP_DTL_SIZE  cascade constraints;
drop table  CNT_CUST  cascade constraints;
drop table  CNT_CUSTOMIZED_PROCESSOR  cascade constraints;
drop table  CNT_CUSTOM_FIELD_DEF  cascade constraints;
drop table  CNT_CUSTOM_FIELD_DEF_ITEM  cascade constraints; 
drop table  CNT_CUST_ADDRESS  cascade constraints; 
drop table  CNT_CUST_ATTACHMENT  cascade constraints;
drop table  CNT_CUST_CONTACT  cascade constraints; 
drop table  CNT_CUST_H  cascade constraints;
drop table  CNT_CUST_HC  cascade constraints;
drop table  CNT_CUST_IMAGE  cascade constraints;
drop table  CNT_DATA_INHERITANCE_PROFILE  cascade constraints;
drop table  CNT_DATA_MAPPING_RULE  cascade constraints;
drop table  CNT_DOC_LOCK  cascade constraints;
drop table  CNT_DOC_UNIT  cascade constraints;
drop table  CNT_DOMAIN  cascade constraints;
drop table  CNT_DOMAIN_ATTRIBUTE  cascade constraints;
drop table  CNT_ENTITY_DEFINITION  cascade constraints; 
drop table  CNT_EVENT_HISTORY  cascade constraints;
drop table  CNT_FACT  cascade constraints; 
drop table  CNT_FACT_ADDRESS  cascade constraints; 
drop table  CNT_FACT_ATTACHMENT  cascade constraints;
drop table  CNT_FACT_AUDIT  cascade constraints;
drop table  CNT_FACT_AUDIT_ATTACHMENT  cascade constraints;
drop table  CNT_FACT_AUDIT_H  cascade constraints;
drop table  CNT_FACT_AUDIT_IMAGE  cascade constraints;
drop table  CNT_FACT_CONTACT  cascade constraints; 
drop table  CNT_FACT_CUST  cascade constraints; 
drop table  CNT_FACT_H  cascade constraints;
drop table  CNT_FACT_HC  cascade constraints;
drop table  CNT_FACT_IMAGE  cascade constraints;
drop table  CNT_FAVORITE  cascade constraints;
drop table  CNT_FIELD_DEFINITION  cascade constraints; 
drop table  CNT_FIELD_MAPPING_RULE  cascade constraints;
drop table  CNT_FIELD_PATH  cascade constraints;
drop table  CNT_FIELD_PATH_ATTRIBUTES  cascade constraints;
drop table  CNT_FIELD_SORTING  cascade constraints;
drop table  CNT_FIELD_SORTINGS  cascade constraints;
drop table  CNT_FORUM  cascade constraints;
drop table  CNT_FORUM_MESSAGE  cascade constraints;
drop table  CNT_FORUM_MESSAGE_ATTACHMENT  cascade constraints;
drop table  CNT_FORUM_MESSAGE_NOTIFY  cascade constraints;
drop table  CNT_FORUM_REF  cascade constraints;
drop table  CNT_FREE_TEXT  cascade constraints;
drop table  CNT_GROUP  cascade constraints;
drop table  CNT_GROUP_DOMAIN  cascade constraints;
drop table  CNT_GROUP_MEMBER  cascade constraints;
drop table  CNT_GROUP_ROLE  cascade constraints;
drop table  CNT_HCL  cascade constraints;
drop table  CNT_HCL_NODE  cascade constraints;
drop table  CNT_HCL_TYPE  cascade constraints;
drop table  CNT_HCL_TYPE_LEVEL  cascade constraints;
drop table  CNT_HIERARCHY  cascade constraints;
drop table  CNT_HIERARCHY_CHILDNODE  cascade constraints;
drop table  CNT_HISTORY_DEF  cascade constraints;  
drop table  CNT_HISTORY_DEF_ITEM  cascade constraints; 
drop table  CNT_IMAGE  cascade constraints;
drop table  CNT_INSPECT_CHECK  cascade constraints;
drop table  CNT_INSPECT_CHECK_CHECKLIST  cascade constraints;
drop table  CNT_INSPECT_CHECK_ITEM  cascade constraints;
drop table  CNT_ITEM  cascade constraints;
drop table  CNT_ITEM_ASSOCIATE_ITEM  cascade constraints;
drop table  CNT_ITEM_ATTACHMENT  cascade constraints;
drop table  CNT_ITEM_CUST  cascade constraints;
drop table  CNT_ITEM_H  cascade constraints;
drop table  CNT_ITEM_IMAGE  cascade constraints;
drop table  CNT_ITEM_MERCH_HC  cascade constraints;
drop table  CNT_ITEM_OTHER  cascade constraints;
drop table  CNT_ITEM_SKU  cascade constraints;
drop table  CNT_ITEM_SOUR_AGENT  cascade constraints;
drop table  CNT_ITEM_VENDOR  cascade constraints;
drop table  CNT_LABEL  cascade constraints;
drop table  CNT_LABEL_PROFILE  cascade constraints;
drop table  CNT_LABEL_PROFILE_BAK  cascade constraints;
drop table  CNT_LABEL_PROFILE_H  cascade constraints;
drop table  CNT_LABEL_PROFILE_RULE  cascade constraints;
drop table  CNT_MEMBER_HCL_NODE  cascade constraints;
drop table  CNT_MEMBER_ROLE  cascade constraints;
drop table  CNT_MEMBER_RULE_DATA  cascade constraints;
drop table  CNT_MODULES  cascade constraints;
drop table  CNT_MODULE_GROUPS  cascade constraints;
drop table  CNT_MPO  cascade constraints;
drop table  CNT_MPO_ADDRESS  cascade constraints;
drop table  CNT_MPO_ATTACHMENT  cascade constraints;
drop table  CNT_MPO_CHARGE  cascade constraints;
drop table  CNT_MPO_CONTACT  cascade constraints;
drop table  CNT_MPO_H  cascade constraints;
drop table  CNT_MPO_ITEM  cascade constraints;
drop table  CNT_MPO_ITEM_COLOR  cascade constraints;
drop table  CNT_MPO_ITEM_CS  cascade constraints;
drop table  CNT_MPO_ITEM_SIZE  cascade constraints;
drop table  CNT_NAVI_ENTRY  cascade constraints;
drop table  CNT_NAVI_MODULE  cascade constraints;
drop table  CNT_OBJECT_OPTION  cascade constraints;
drop table  CNT_OS  cascade constraints;
drop table  CNT_OS_ADDRESS  cascade constraints;
drop table  CNT_OS_ATTACHMENT  cascade constraints;
drop table  CNT_OS_CHARGE  cascade constraints;
drop table  CNT_OS_CONTACT  cascade constraints;
drop table  CNT_OS_H  cascade constraints;
drop table  CNT_OS_ITEM  cascade constraints;
drop table  CNT_OS_ITEM_COLOR  cascade constraints;
drop table  CNT_OS_ITEM_CS  cascade constraints;
drop table  CNT_OS_ITEM_SIZE  cascade constraints;
drop table  CNT_PROCESSOR_TEMPLATE  cascade constraints;
drop table  CNT_QC  cascade constraints;
drop table  CNT_QC_CHECKLIST  cascade constraints;
drop table  CNT_QC_ITEM  cascade constraints;
drop table  CNT_QC_ITEM_CHECKLIST  cascade constraints;
drop table  CNT_QC_TEMPLATE  cascade constraints;
drop table  CNT_QC_TEMPLATE_DETAIL  cascade constraints;
drop table  CNT_QC_TEMPLATE_RULE  cascade constraints;
drop table  CNT_READ_MARK  cascade constraints;
drop table  CNT_RECENT_ACCESS  cascade constraints;
drop table  CNT_RFQ  cascade constraints;
drop table  CNT_RFQ_H  cascade constraints;
drop table  CNT_RFQ_ITEM  cascade constraints;
drop table  CNT_RFQ_VENDOR  cascade constraints;
drop table  CNT_ROLE  cascade constraints;
drop table  CNT_RULE_ACTION  cascade constraints;
drop table  CNT_RULE_FIELD_DENY  cascade constraints;
drop table  CNT_RULE_UI  cascade constraints;
drop table  CNT_SCHEDULER  cascade constraints;
drop table  CNT_SELECTION  cascade constraints;
drop table  CNT_SEQ_DEF  cascade constraints;
drop table  CNT_SHIP  cascade constraints;
drop table  CNT_SHIP_ATTACHMENT  cascade constraints;
drop table  CNT_SHIP_H  cascade constraints;
drop table  CNT_SHIP_ITEM  cascade constraints;
drop table  CNT_SHIP_ITEM_COLOR  cascade constraints;
drop table  CNT_SHIP_ITEM_CS  cascade constraints;
drop table  CNT_SHIP_ITEM_SIZE  cascade constraints;
drop table  CNT_SPEC  cascade constraints;
drop table  CNT_SPEC_ATTACHMENT  cascade constraints;
drop table  CNT_SPEC_COLOR  cascade constraints;
drop table  CNT_SPEC_COMP  cascade constraints;
drop table  CNT_SPEC_GRADING  cascade constraints;
drop table  CNT_SPEC_H  cascade constraints;
drop table  CNT_SPEC_IMAGE  cascade constraints;
drop table  CNT_SPEC_LABEL  cascade constraints;
drop table  CNT_SPEC_MEAS  cascade constraints;
drop table  CNT_SPEC_OTHER  cascade constraints;
drop table  CNT_SPEC_REQUIREMENT  cascade constraints;
drop table  CNT_SPEC_REQUIREMENT_BAK  cascade constraints;
drop table  CNT_SPEC_SIZE  cascade constraints;
drop table  CNT_SPEC_TEMPLATE  cascade constraints;
drop table  CNT_SPEC_TEMPLATE_DETAIL  cascade constraints;
drop table  CNT_SPEC_TEMPLATE_H  cascade constraints;
drop table  CNT_SPEC_TEMPLATE_RULE  cascade constraints;
drop table  CNT_SYSTEM_MESSAGE  cascade constraints;
drop table  CNT_TRIGGER  cascade constraints;
drop table  CNT_TRIGGER_ACTION  cascade constraints;
drop table  CNT_TRIGGER_ACTION_QUEUE  cascade constraints;
drop table  CNT_TRIGGER_ACTION_QUEUE_LOCK  cascade constraints;
drop table  CNT_TRIGGER_LISTENER  cascade constraints;
drop table  CNT_TRIGGER_LISTENER_CRITERIA  cascade constraints;
drop table  CNT_USER  cascade constraints;
drop table  CNT_USER_ATTRIBUTE  cascade constraints;
drop table  CNT_USER_CACHED_RULES  cascade constraints;
drop table  CNT_USER_DOMAINS  cascade constraints;
drop table  CNT_USER_HC  cascade constraints;
drop table  CNT_USER_HCL_NODES  cascade constraints;
drop table  CNT_VALIDATION_FIELD  cascade constraints;
drop table  CNT_VALIDATION_FIELD_PARAM  cascade constraints;
drop table  CNT_VALIDATION_PROFILE  cascade constraints;
drop table  CNT_VALIDATION_RULE  cascade constraints;
drop table  CNT_VENDOR  cascade constraints; 
drop table  CNT_VENDOR_ADDRESS  cascade constraints; 
drop table  CNT_VENDOR_ATTACHMENT  cascade constraints;
drop table  CNT_VENDOR_CONTACT  cascade constraints; 
drop table  CNT_VENDOR_CUST  cascade constraints; 
drop table  CNT_VENDOR_FACT  cascade constraints; 
drop table  CNT_VENDOR_H  cascade constraints;
drop table  CNT_VENDOR_HC  cascade constraints;
drop table  CNT_VENDOR_IMAGE  cascade constraints;
drop table  CNT_VIEW  cascade constraints;
drop table  CNT_VIEW_ACTION  cascade constraints;
drop table  CNT_VIEW_COLUMN  cascade constraints;
drop table  CNT_VIEW_OPTION  cascade constraints;
drop table  CNT_VIEW_SORTING  cascade constraints;
drop table  CNT_VPO  cascade constraints;
drop table  CNT_VPO_ADDRESS  cascade constraints;
drop table  CNT_VPO_ATTACHMENT  cascade constraints;
drop table  CNT_VPO_CHARGE  cascade constraints;
drop table  CNT_VPO_CONTACT  cascade constraints;
drop table  CNT_VPO_DC  cascade constraints;
drop table  CNT_VPO_DC_DTL  cascade constraints;
drop table  CNT_VPO_H  cascade constraints;
drop table  CNT_VPO_ITEM  cascade constraints;
drop table  CNT_VPO_ITEM_COLOR  cascade constraints;
drop table  CNT_VPO_ITEM_CS  cascade constraints;
drop table  CNT_VPO_ITEM_SIZE  cascade constraints;
drop table  CNT_VPO_SHIP  cascade constraints;
drop table  CNT_VPO_SHIP_DC  cascade constraints;
drop table  CNT_VPO_SHIP_DTL  cascade constraints;
drop table  CNT_VPO_SHIP_DTL_COLOR  cascade constraints;
drop table  CNT_VPO_SHIP_DTL_CS  cascade constraints;
drop table  CNT_VPO_SHIP_DTL_SIZE  cascade constraints;
drop table  CNT_VQ  cascade constraints;
drop table  CNT_VQ_ATTACHMENT  cascade constraints;
drop table  CNT_VQ_CARTON  cascade constraints;
drop table  CNT_VQ_COMPONENT  cascade constraints;
drop table  CNT_VQ_COST_ELEMENT  cascade constraints;
drop table  CNT_VQ_COST_ELEMENT_SUM  cascade constraints;
drop table  CNT_VQ_H  cascade constraints;
drop table  CNT_VQ_IMAGE  cascade constraints;
drop table  CNT_VQ_ITEM  cascade constraints;
drop table  CNT_VQ_REMARK  cascade constraints;
drop table  CNT_CODELIST_BOOK_H  cascade constraints;
drop table  CNT_CODELIST_LINK_INFO  cascade constraints;
drop table  CNT_CI_ITEM_SIZE  cascade constraints;
drop table  CNT_CODELIST  cascade constraints;
drop table  CNT_CODELIST_BOOK  cascade constraints;
drop table  CNT_CI_ITEM_CS  cascade constraints;
drop table  CNT_CI_ITEM  cascade constraints;
drop table  CNT_CI_ITEM_COLOR  cascade constraints;
drop table  CNT_CI_H  cascade constraints;
drop table  CNT_CI_CONTACT  cascade constraints;
drop table  CNT_CI_CHARGE  cascade constraints;
drop table  CNT_CI_ATTACHMENT  cascade constraints;
drop table  CNT_CI_ADDRESS  cascade constraints;
drop table  CNT_CI  cascade constraints;
drop table  CNT_CBX_SAMPLE_ITEMB  cascade constraints;
drop table  CNT_CBX_SAMPLE_ITEMA  cascade constraints;
drop table  CNT_CBX_SAMPLE_H  cascade constraints;
drop table  CNT_CBX_SAMPLE  cascade constraints;
drop table  CNT_BRIEF_VENDOR  cascade constraints;
drop table  CNT_BRIEF_SOUR_AGENT  cascade constraints;
drop table  CNT_BRIEF_MERCH_HC  cascade constraints;
drop table  CNT_BRIEF_IMAGE  cascade constraints;
drop table  CNT_BRIEF_H  cascade constraints;
drop table  CNT_BRIEF_CUST  cascade constraints;
drop table  CNT_BRIEF_ATTACHMENT  cascade constraints;
drop table  CNT_BRIEF  cascade constraints;
drop table  CNT_AUDIT_LOG_FIELD  cascade constraints;
drop table  CNT_AUDIT_LOG  cascade constraints;
drop table  CNT_AUDIT_CONFIG_FIELD  cascade constraints;
drop table  CNT_AUDIT_CONFIG  cascade constraints;
drop table  CNT_AUDIT_CHAIN  cascade constraints;
drop table  CNT_ATTACHMENT_DATA  cascade constraints;
drop table  CNT_ATTACHMENT  cascade constraints;
drop table  CNT_APRV_TYPE_FIELD  cascade constraints;
drop table  CNT_APRV_TYPE  cascade constraints;
drop table  CNT_APRV_TEMPL_STAGE  cascade constraints;
drop table  CNT_APRV_TEMPL_MATCH_RULE  cascade constraints;
drop table  CNT_APRV_TEMPL  cascade constraints;
drop table  CNT_APRV_STAGE_APPROVER  cascade constraints;
drop table  CNT_APRV_STAGE  cascade constraints;
drop table  CNT_APRV_PROFILE  cascade constraints;
drop table  CNT_ADVANCED_SEARCH_H  cascade constraints;
drop table  CNT_ADVANCED_SEARCH_COLUMN  cascade constraints;
drop table  CNT_ACTION_MAP  cascade constraints;
drop table  CNT_ADVANCED_SEARCH  cascade constraints;
drop table  CNT_ACCESS_OBJ_RES_CONDITION  cascade constraints;
drop table  CNT_ACCESS_OBJECT_ACTION  cascade constraints;
drop table  CNT_ACCESS_OBJECT_CONDITION  cascade constraints;
drop table  CNT_ACCESS_OBJECT_RESOURCE  cascade constraints;
drop table  CNT_ACCESS_OBJECT  cascade constraints;
drop table  CNT_CPO_H  cascade constraints;
drop table  CNT_CPO_ITEM  cascade constraints;
drop table  CNT_CODELIST_TYPE  cascade constraints;
drop table  CNT_CODELIST_TYPE_ITEM  cascade constraints;
drop table  CNT_COMMAND_HANDLER  cascade constraints;
drop table  CNT_COMMAND_LISTENER  cascade constraints;
drop table  CNT_COMMAND_LOG  cascade constraints;
drop table  CNT_COMMAND_LOG_ARC  cascade constraints;
drop table  CNT_COMMAND_LOG_ERROR  cascade constraints;
drop table  CNT_COMMAND_LSNT_HDLR  cascade constraints;
drop table  CNT_COMMAND_PROPERTY  cascade constraints;
drop table  CNT_COMMAND_ROUTER  cascade constraints;
drop table  CNT_COMMIT  cascade constraints;
drop table  CNT_COMMIT_ADDRESS  cascade constraints;
drop table  CNT_COMMIT_ATTACHMENT  cascade constraints;
drop table  CNT_COMMIT_CHARGE  cascade constraints;
drop table  CNT_COMMIT_CONTACT  cascade constraints;
drop table  CNT_COMMIT_H  cascade constraints;
drop table  CNT_COMMIT_ITEM  cascade constraints;
drop table  CNT_CONDITION  cascade constraints;
drop table  CNT_COST_SHEET_TEMPLATE  cascade constraints;
drop table  CNT_COST_SHEET_TEMPLATE_DETAIL  cascade constraints;
drop table  CNT_COST_SHEET_TEMPLATE_H  cascade constraints;
drop table  CNT_COST_SHEET_TEMPLATE_RULE  cascade constraints;
drop table  CNT_CPM_ATTACHMENT  cascade constraints;
drop table  CNT_CPM_COLOR_PRIORITY  cascade constraints;
drop table  CNT_CPM_COLOR_PRIORITY_H  cascade constraints;
drop table  CNT_CPM_DOC  cascade constraints;
drop table  CNT_CPM_DOC_H  cascade constraints;
drop table  CNT_CPM_HISTORY  cascade constraints;
drop table  CNT_CPM_IMAGE  cascade constraints;
drop table  CNT_CPM_TASK  cascade constraints;
drop table  CNT_CPM_TASK_ACTIVITY  cascade constraints;
drop table  CNT_CPM_TASK_ALERT  cascade constraints;
drop table  CNT_CPM_TASK_FTL  cascade constraints;
drop table  CNT_CPM_TASK_FTL_H  cascade constraints;
drop table  CNT_CPM_TASK_H  cascade constraints;
drop table  CNT_CPM_TASK_TEMPL  cascade constraints;
drop table  CNT_CPM_TASK_TEMPL_FIELD  cascade constraints;
drop table  CNT_CPM_TASK_TEMPL_H  cascade constraints;
drop table  CNT_CPM_TASK_TRIGGER  cascade constraints;
drop table  CNT_CPM_TEMPL  cascade constraints;
drop table  CNT_CPM_TEMPL_H  cascade constraints;
drop table  CNT_CPM_TEMPL_MATCH_RULE  cascade constraints;
drop table  CNT_CPM_TEMPL_TASK  cascade constraints;
drop table  CNT_CPM_TEMPL_TASK_TRIGGER  cascade constraints;
drop table  CNT_CPO  cascade constraints;
drop table  CNT_CPO_ADDRESS  cascade constraints;
drop table  CNT_CPO_ATTACHMENT  cascade constraints;
drop table  CNT_CPO_CHARGE  cascade constraints;
drop table  CNT_CPO_CONTACT  cascade constraints;
drop table  CNT_CPO_DC  cascade constraints;
drop table  CNT_CPO_DC_DTL  cascade constraints;


drop table  CNT_ACCESS_OBJECT_H   cascade constraints;           
drop table  CNT_AUDIT_CONFIG_H   cascade constraints;            
drop table  CNT_CONDITION_H      cascade constraints;            
drop table  CNT_DATA_INHERITANCE_PROFILE_H   cascade constraints;
drop table  CNT_DATA_MAPPING_RULE_H          cascade constraints;
drop table  CNT_DOC_LOCK_H           cascade constraints;        
drop table  CNT_GROUP_H             cascade constraints;         
drop table  CNT_NAVI_MODULE_H        cascade constraints;        
drop table  CNT_NOTIFICATION_PROFILE       cascade constraints;  
drop table  CNT_NOTIFICATION_REF_DOC      cascade constraints; 
drop table  CNT_NOTIFICATION_ATTACHMENT     cascade constraints; 
drop table  CNT_NOTIFICATION_TO_USER     cascade constraints;    
drop table  CNT_NOTIFICATION       cascade constraints;          
drop table  CNT_NOTIFICATION_TO_EMAIL      cascade constraints; 
drop table  CNT_ROLE_H     cascade constraints;                  
drop table  CNT_USER_H  cascade constraints;

DROP SEQUENCE CBX_SEQ_CBX_SAMPLE_CODE;
DROP SEQUENCE CBX_SEQ_CI_CODE;
DROP SEQUENCE CBX_SEQ_COMMITMENT_NO;
DROP SEQUENCE CBX_SEQ_CPO_CPO_NO;
DROP SEQUENCE CBX_SEQ_CPO_PO_NO;
DROP SEQUENCE CBX_SEQ_CPO_VPO_NO;
DROP SEQUENCE CBX_SEQ_CUST_CODE;
DROP SEQUENCE CBX_SEQ_FACT_AUDIT_CODE;
DROP SEQUENCE CBX_SEQ_FACT_CODE;
DROP SEQUENCE CBX_SEQ_IC_CODE;
DROP SEQUENCE CBX_SEQ_ITEM_CODE;
DROP SEQUENCE CBX_SEQ_MPO_MPO_NO;
DROP SEQUENCE CBX_SEQ_OFFER_SHEET_NO;
DROP SEQUENCE CBX_SEQ_QC_CODE;
DROP SEQUENCE CBX_SEQ_RFQ_NO;
DROP SEQUENCE CBX_SEQ_SHIP_CODE;
DROP SEQUENCE CBX_SEQ_VENDOR_CODE;
DROP SEQUENCE CBX_SEQ_VPO_VPO_NO;
DROP SEQUENCE CBX_SEQ_VQ_NO;
DROP SEQUENCE CBX_TEST_GENERATOR;
DROP SEQUENCE CBX_SEQ_BRIEF_CODE;

DROP VIEW V_USER_RULE;
DROP VIEW V_USER_ROLE;
DROP VIEW V_USER_GROUP;














