CREATE OR REPLACE PROCEDURE SP_GEN_DATALISTTYPE ( 
   IN_DOMAIN_ID VARCHAR2 
)
AS 
BEGIN 

    
  UPDATE TMP_DATA_LIST_TYPE TMP SET TMP.CODELIST_TYPE_ID = NVL((SELECT MAX(CDTYPE.ID) 
  FROM CNT_CODELIST_TYPE CDTYPE WHERE CDTYPE.DOMAIN_ID = 'GIANI' 
  AND CDTYPE.TYPE = TMP.DATALISTTYPE), LOWER(SYS_GUID()))
  ;
  
  UPDATE TMP_DATA_LIST_TYPE TMP SET TMP.CODELIST_TYPE_ITEM_ID = NVL((SELECT MAX(TYPEITEM.ID)
  FROM CNT_CODELIST_TYPE_ITEM TYPEITEM WHERE TYPEITEM.DOMAIN_ID = 'GIANI'
  AND TYPEITEM.PARENT_ID = TMP.CODELIST_TYPE_ID 
  AND TYPEITEM.COLUMN_NAME = 'cust' || TMP.DATA_TYPE ||DECODE(MOD(TO_NUMBER(TRIM(REPLACE(UPPER(TMP.FIELD), 'COLUMN', ''))), 10), 0, 10, MOD(TO_NUMBER(TRIM(REPLACE(UPPER(TMP.FIELD), 'COLUMN', ''))), 10))
  ), LOWER(SYS_GUID()))
  WHERE TMP.FIELD 
  IN ('Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6', 'Column 7'
  ,'Column 11', 'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16'
  ,'Column 21', 'Column 22', 'Column 23', 'Column 24', 'Column 25', 'Column 26', 'Column 27')
  ;

  UPDATE TMP_DATA_LIST_TYPE TMP  SET TMP.CODELIST_TYPE_ID = (SELECT TMP2.CODELIST_TYPE_ID FROM 
  (SELECT DATALISTTYPE, MAX(CODELIST_TYPE_ID) CODELIST_TYPE_ID FROM TMP_DATA_LIST_TYPE GROUP BY DATALISTTYPE) TMP2 
  WHERE TMP2.DATALISTTYPE = TMP.DATALISTTYPE
  )
  WHERE NOT EXISTS (SELECT 1 FROM CNT_CODELIST_TYPE CDTYPE WHERE CDTYPE.ID = TMP.CODELIST_TYPE_ID)
  ;
         
  INSERT INTO CNT_CODELIST_TYPE 
  (ID, REVISION, ENTITY_VERSION, DOMAIN_ID, STATUS, DOC_STATUS, EDITING_STATUS, CREATE_USER,  CREATED_ON, TYPE, DESCRIPTION)
  SELECT TMP.CODELIST_TYPE_ID, 1 REVISION, 1 ENTITY_VERSION, 'GIANI', 'active', 'active', NULL, 'system', SYSDATE, MAX(TMP.DATALISTTYPE), MAX(TMP.DESCRIPTION)
  FROM TMP_DATA_LIST_TYPE TMP 
  WHERE NOT EXISTS (SELECT 1 FROM CNT_CODELIST_TYPE CDTYPE WHERE CDTYPE.ID = TMP.CODELIST_TYPE_ID)
  GROUP BY TMP.CODELIST_TYPE_ID
  ;
  
  INSERT INTO CNT_CODELIST_TYPE_ITEM
  (ID, PARENT_ID, REVISION, ENTITY_VERSION, DOMAIN_ID, COLUMN_NAME, DATA_TYPE, LABEL, SHOW, MANDATORY)
  SELECT TMP.CODELIST_TYPE_ITEM_ID, TMP.CODELIST_TYPE_ID, 1 REVISION, 1 ENTITY_VERSION, 'GIANI' DOMAIN_ID
  , 'cust' || DATA_TYPE||DECODE(MOD(TO_NUMBER(TRIM(REPLACE(UPPER(FIELD), 'COLUMN', ''))), 10), 0, 10, MOD(TO_NUMBER(TRIM(REPLACE(UPPER(FIELD), 'COLUMN', ''))), 10))  COLUMN_NAME
  ,DATA_TYPE, FIELD_LABEL, DECODE(NVL(NOT_AVAILABLE, 'Y'), 'Y', 0, 1) SHOW, DECODE(NVL(MANDATORY, 'N'), 'N', 0, 1)MANDATORY 
  FROM TMP_DATA_LIST_TYPE TMP 
  WHERE  TMP.FIELD IN ('Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6', 'Column 7'
  ,'Column 11', 'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16'
  ,'Column 21', 'Column 22', 'Column 23', 'Column 24', 'Column 25', 'Column 26', 'Column 27')
  AND NOT EXISTS (SELECT 1 FROM CNT_CODELIST_TYPE_ITEM TYPEITEM WHERE TYPEITEM.ID = TMP.CODELIST_TYPE_ITEM_ID)
  ;       
    
EXCEPTION
   WHEN OTHERS
   THEN
   RAISE_APPLICATION_ERROR(-20001, SQLERRM); 
END;
/