ALTER TABLE CNT_CI_ITEM DROP COLUMN S_A_SHIP_ITEM_ID;
ALTER TABLE CNT_CI_ITEM DROP COLUMN S_A_SHIP_ITEM_REF;
ALTER TABLE CNT_CI_ITEM DROP COLUMN S_A_SHIP_ITEM_VER;
ALTER TABLE CNT_CI_ITEM DROP COLUMN S_A_SHIP_ITEM_REF2;
ALTER TABLE CNT_CI_ITEM ADD S_A_SHIP_ITEM_ID CHAR(32);
ALTER TABLE CNT_CI_ITEM MODIFY ITEM_DESC NVARCHAR2(1000);
