--DELETE FROM CNT_USER_CACHED_RULES;
--DELETE CNT_USER_HCL_NODES;
DELETE CNT_DOMAIN_GROUP_CACHED_RULES;
--DELETE CNT_SERIALIZED_ENTITY;

DELETE FROM CNT_SERIALIZED_ENTITY WHERE TARGET_ENTITY IN ('UserCacheData', 'ChecksumCacheData', 'View', 'CodelistBook', 'Hcl', 
	'AccessObject', 'DefaultProfile', 'HclType', 'DataListType', 'ValidationProfile', 'QueryCountCache', 'FormatProfile', 'AuditConfig', 'NaviModule', 'Condition', 'HistoryDef', 'DataMappingRule', 
	'DataInheritanceProfile');

DELETE FROM CNT_CHECKSUM_CACHE_RULE;
DELETE FROM CNT_CHECKSUM_CACHE_HCL_NODE;
DELETE FROM CNT_CHECKSUM_CACHE_DATA;

DELETE CNT_USER_CACHE_RULE;
DELETE CNT_USER_CACHE_HCL_NODE;
DELETE CNT_USER_CACHE_DATA;

--UPDATE CNT_USER SET REFRESH_CACHE = 1;

COMMIT;
