--------------------------- Begin CNT-10596 ---------------------------------
CREATE INDEX IDX_SESSION_INFO_SESSION_ID ON CNT_SESSION_INFO (SESSION_ID);

CREATE INDEX IDX_SESSION_INFO_DOMAIN_ID ON CNT_SESSION_INFO (DOMAIN_ID);

CREATE INDEX IDX_SESSION_INFO_USER_ID ON CNT_SESSION_INFO (USER_ID);

CREATE INDEX IDX_SESSION_INFO_EXPIRED ON CNT_SESSION_INFO (EXPIRED);
--------------------------- End CNT-10596 ------------------------------------


--CNT-11072--------
UPDATE CNT_VPO_ACK_SHIP SET VPO_SHIP_ID = VPO_SHIP_ID_BACKUP;
UPDATE CNT_VPO_ACK_SHIP_DTL SET VPO_SHIP_DTL_ID = VPO_SHIP_DTL_ID_BACKUP;

ALTER TABLE CNT_VPO_ACK_SHIP DROP COLUMN VPO_SHIP_ID_BACKUP;
ALTER TABLE CNT_VPO_ACK_SHIP_DTL DROP COLUMN VPO_SHIP_DTL_ID_BACKUP;

--end of CNT-11072--------