--------------------------- Begin CNT-10596 ---------------------------------
CREATE INDEX IDX_SESSION_INFO_SESSION_ID ON CNT_SESSION_INFO (SESSION_ID);

CREATE INDEX IDX_SESSION_INFO_DOMAIN_ID ON CNT_SESSION_INFO (DOMAIN_ID);

CREATE INDEX IDX_SESSION_INFO_USER_ID ON CNT_SESSION_INFO (USER_ID);

CREATE INDEX IDX_SESSION_INFO_EXPIRED ON CNT_SESSION_INFO (EXPIRED);
--------------------------- End CNT-10596 ------------------------------------